### ISSUE TITLE
Logging in issue - ver. 1.1.58

### ISSUE THREAD

**Issue by ambarusa** [marcelveldt/plugin.audio.spotify#100]
Hello, I'm havinng issues logging in to Spotify on my Kodi 17 (Rpi3 & OSMC). The add-on is installed from the repo, the version is 1.1.58. I can't connect from my phone either. Here is the log file

11:15:17.853 T:1696592640   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Py
thon callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEM
ORY LEAKS!
                                            Error Type: <type 'exceptions.SyntaxEr
ror'>
                                            Error Contents: unexpected EOF while p
arsing (<string>, line 0)
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin
.audio.spotify/service.py", line 14, in <module>
                                                MainService()
                                              File "/home/osmc/.kodi/addons/plugin
.audio.spotify/resources/lib/main_service.py", line 60, in __init__
                                                self.renew_token()
                                              File "/home/osmc/.kodi/addons/plugin
.audio.spotify/resources/lib/main_service.py", line 167, in renew_token
                                                username = self.get_username()
                                              File "/home/osmc/.kodi/addons/plugin
.audio.spotify/resources/lib/main_service.py", line 134, in get_username
                                                username = self.spotty.get_usernam
e()
                                              File "/home/osmc/.kodi/addons/plugin
.audio.spotify/resources/lib/utils.py", line 522, in get_username
                                                data = eval(data)
                                              File "<string>", line 0

                                                ^
                                            SyntaxError: unexpected EOF while pars
ing
                                            -->End of Python script error report<-
-
11:15:23.914 T:1713369856 WARNING: CSkinInfo: failed to load skin settings

**Comment by marcelveldt** [comment]
this version has just been fixed in a PR that was submitted. I'll put up a new version on the repo.
For now, just delete the contents of the plugin.audio.spotify in Kodi's userdata/addon_data

**Comment by ambarusa** [comment]
thanks! I'll clean it up, and wait the update.
