### ISSUE TITLE
Add on will not load after installed and username/password are set.

### ISSUE THREAD

**Issue by webivation** [marcelveldt/plugin.audio.spotify#13]
[kodilog.txt](https://github.com/marcelveldt/plugin.audio.spotify/files/658897/kodilog.txt)

I attached a full log dump.  Application just sits there and spins for a while, then errors out.

**Comment by marcelveldt** [comment]
You need to have a webbrowser installed, see the forum for details.
This will be improved in the near future with an intermediate service but for this time you either need to have a webbrowser installed or use a other setup to create the cached credentials. See forum, first post " workaround for raspberry pi"

**Comment by webivation** [comment]
Does it not work with the Web Viewer from the Kodi repo?

**Comment by marcelveldt** [comment]
nope, you need a real webbrowser. So no support for OSMC.
See the forum, there's a workaround there for pi users

**Comment by marcelveldt** [comment]
http://forum.kodi.tv/showthread.php?tid=265356&pid=2289336#pid2289336
