### ISSUE TITLE
Song order on Kore

### ISSUE THREAD

**Issue by regagain** [marcelveldt/plugin.audio.spotify#15]
Hi!

When browsing albums on [Kore](https://github.com/xbmc/Kore/) (the official Android remote), the songs are listed alphabetically.
Can this be fixed on your side or is that a Kore issue?

**Comment by regagain** [comment]
Same issue with playlists, by the way.

**Comment by timmken** [comment]
Listing by "date added" would also be highly appreciated.

**Comment by mklemenz** [comment]
Kore does use the jsonrpc api from kodi - which returns all items in the correct order. so the sorting then is done by Kore.
