### ISSUE TITLE
Seek step doesn't work

### ISSUE THREAD

**Issue by regagain** [marcelveldt/plugin.audio.spotify#16]
Forward/backward seek step (i.e. pressing right or left on the keyboard) during playback does not work.
Is this a libspotify limitation?

PS: Thank you for this great addon!

**Comment by marcelveldt** [comment]
Yes, it isn't implemented and I'm not interested in trying to make it work with the crappy lib spotify implementation there is now. Maybe the future will bring us some better SDK to handle the playback.
