### ISSUE TITLE
Support Spotify Connect

### ISSUE THREAD

**Issue by marcelveldt** [marcelveldt/plugin.audio.spotify#20]
Spotify finaly launched the webapi support of controlling connect devices.

https://developer.spotify.com/web-api/web-api-connect-endpoint-reference/

This adds the ability to control other spotify devices such as the android client

**Comment by marcelveldt** [comment]
fixed in 1.1.0

**Comment by michaelphines** [comment]
How can I make the plugin use the Kodi player again after it's been controlling a Connect device?

**Comment by marcelveldt** [comment]
You can select the player in the addon itself. There's an entry called "Playback device" 
Just set it to local playback again.

**Comment by michaelphines** [comment]
I guess the problem then is that I don't have an option for "Local Playback".

![doc - jun 9 2017 - 3-11 pm](https://user-images.githubusercontent.com/281513/26992877-2fc4e628-4d26-11e7-86b1-4fb237e4a3e1.jpg)
Sorry for potato quality

**Comment by marcelveldt** [comment]
What platform do you have it installed ? Note that local playback is not supported on Android and iOS. In that case you need to install the native spotify app in the background (and control playback with Connect).

**Comment by michaelphines** [comment]
Ah, okay. It's running on a FireTV, so that's obviously the issue.

**Comment by marcelveldt** [comment]
Yes, indeed. Just install the Spotify app from the store and you can control it's playback with the Kodi add-on. Maybe some day I can implement native playback for those platforms within Kodi but for now that's almost impossible.
