### ISSUE TITLE
Problem logging in with username containing international characters

### ISSUE THREAD

**Issue by Alphix** [marcelveldt/plugin.audio.spotify#23]
Hi,

I'm testing your plugin (1.0.26) on Kodi 17.3 and I'm having issues with logging in for the first time using a username with international characters. I know this issue has already been discussed in the forum, but there it appears to have been fixed in 2016. Could it be that the issue has resurfaced?

The error message is (after enabling extra debug output):

`22:44:10.964 T:140443871549184  NOTICE: Spotify --> Your platform (x86_64 System.Platform.Linux)
22:44:11.543 T:140443871549184  NOTICE: Spotify --> Starting background service...
22:44:11.547 T:140443871549184  NOTICE: Spotify --> Checking remembered_user ..
22:44:11.548 T:140443871549184  NOTICE: Spotify --> TRACE:   File "/home/david/.kodi/addons/plugin.audio.spotify/spotifyservice.py", line 9, in <module>
                                                service.main()
                                              File "/home/david/.kodi/addons/plugin.audio.spotify/resources/playbackservice.py", line 286, in main
                                                logMsg("TRACE: " + ( ''.join(traceback.format_stack()) ) )
22:44:11.548 T:140443871549184  NOTICE: Spotify --> EXCEPTION in background service: argument 2: <type 'exceptions.UnicodeEncodeError'>: 'ascii' codec can't encode character u'\xe4' in position 6: ordinal not in range(128)
22:44:11.548 T:140443871549184   ERROR: Traceback (most recent call last):
22:44:11.548 T:140443871549184   ERROR:   File "/home/david/.kodi/addons/plugin.audio.spotify/resources/playbackservice.py", line 227, in main
22:44:11.548 T:140443871549184   ERROR:     if not do_login(sess, app):
22:44:11.548 T:140443871549184   ERROR:   File "/home/david/.kodi/addons/plugin.audio.spotify/resources/playbackservice.py", line 143, in do_login
22:44:11.548 T:140443871549184   ERROR:     session.login(username, password, True)
22:44:11.548 T:140443871549184   ERROR:   File "/home/david/.kodi/addons/plugin.audio.spotify/resources/libs/spotify/utils/decorators.py", line 23, in __call__
22:44:11.548 T:140443871549184   ERROR:     result = self._func(*args, **kwargs)
22:44:11.548 T:140443871549184   ERROR:   File "/home/david/.kodi/addons/plugin.audio.spotify/resources/libs/spotify/session.py", line 325, in login
22:44:11.548 T:140443871549184   ERROR:     self.__session_struct, username, password, remember_me, blob
22:44:11.548 T:140443871549184   ERROR:   File "/home/david/.kodi/addons/plugin.audio.spotify/resources/libs/_spotify/session.py", line 146, in login
22:44:11.548 T:140443871549184   ERROR:     )(*args)
22:44:11.548 T:140443871549184   ERROR: ArgumentError: argument 2: <type 'exceptions.UnicodeEncodeError'>: 'ascii' codec can't encode character u'\xe4' in position 6: ordinal not in range(128)
22:44:11.555 T:140443484419840   ERROR: Exception in thread Thread-1:
                                            Traceback (most recent call last):
                                              File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
                                                self.run()
                                              File "/home/david/.kodi/addons/plugin.audio.spotify/resources/playbackservice.py", line 103, in run
                                                self.__mainloop.loop(self.__session)
                                              File "/home/david/.kodi/addons/plugin.audio.spotify/resources/libs/spotify/__init__.py", line 166, in loop
                                                timeout = session.process_events()
                                            ReferenceError: weakly-referenced object no longer exists
22:44:11.556 T:140443871549184  NOTICE: Spotify --> Background service stopped
`

As a workaround, I edited
~/.kodi/addons/plugin.audio.spotify/resources/playbackservice.py

And if I change line 142 (i.e. second last line in do_login()) from:
`
session.login(username, password, True)
`
to
`
session.login(SETTING("username"), password, True)
`

i.e. to not use a username which has been decoded from utf-8...then it works...

**Comment by marcelveldt** [comment]
Later today or tomorrow there will be a new version of the addon available in which this should be fixed.
