### ISSUE TITLE
does not start on Rpi2

### ISSUE THREAD

**Issue by dkadioglu** [marcelveldt/plugin.audio.spotify#25]
Hi,

on my Rpi2 (OSMC, Kodi Leia), the addon does not start with the following error: 

`12:39:12.771 T:1247802352   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: an integer is required
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.audio.spotify/service.py", line 13, in <module>
                                                MainService()
                                              File "/home/osmc/.kodi/addons/plugin.audio.spotify/resources/lib/main_service.py", line 42, in __init__
                                                self.spotty = Spotty()
                                              File "/home/osmc/.kodi/addons/plugin.audio.spotify/resources/lib/utils.py", line 348, in __init__
                                                self.__spotty_binary = self.get_spotty_binary()
                                              File "/home/osmc/.kodi/addons/plugin.audio.spotify/resources/lib/utils.py", line 409, in get_spotty_binary
                                                log_msg(__name__, exc)
                                              File "/home/osmc/.kodi/addons/plugin.audio.spotify/resources/lib/utils.py", line 77, in log_msg
                                                xbmc.log("%s --> %s" % (ADDON_ID, msg), level=loglevel)
                                            TypeError: an integer is required
                                            -->End of Python script error report<--
`

I removed its settings and data -> still the same
I reinstalled -> the same

Thanks in advance!

**Comment by marcelveldt** [comment]
I've just uploaded version 1.1.10 to the repo, that should fix the issue. Please let me know.

**Comment by dkadioglu** [comment]
Thanks for the immediate response! Now I get the following:

`
13:47:49.387 T:1696986096 WARNING: plugin.audio.spotify --> Exception in utils ! --> [Errno 13] Permission denied
13:47:50.748 T:1917842416  NOTICE: CAESinkPi:AddPackets Underrun (delay:0.00 frames:1102)
13:47:52.252 T:1696986096 WARNING: plugin.audio.spotify --> Exception in utils ! --> [Errno 13] Permission denied
13:47:52.253 T:1696986096  NOTICE: plugin.audio.spotify --> Failed to detect architecture or platform not supported !
13:47:52.260 T:1580200944  NOTICE: [plugin.video.youtube] Startup: detected Krypton (Kodi-18.0), setting DASH_SUPPORT_BUILTIN = False, DASH_SUPPORT_ADDON = True
13:47:52.287 T:1257366512  NOTICE: plugin.audio.spotify --> Audio proxy started on port 52308
13:47:53.058 T:1696986096  NOTICE: plugin.audio.spotify --> Launching system-default browser
13:47:53.060 T:1696986096  NOTICE: plugin.audio.spotify --> Waiting for authentication token...
`

**Comment by marcelveldt** [comment]
There is another update available

**Comment by dkadioglu** [comment]
Using the fix from https://forum.kodi.tv/showthread.php?tid=265356&pid=2596731#pid2596731 and version 1.11 made it work! Thank you very much for your work! I'm excited about testing it now.
