### ISSUE TITLE
exception in player_monitor.py

### ISSUE THREAD

**Issue by prometheanfire** [marcelveldt/plugin.audio.spotify#26]
15:57:26.136 T:546894065888   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: 'NoneType' object has no attribute '__getitem__'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.audio.spotify/resources/lib/player_monitor.py", line 49, in onPlayBackStarted
                                                self.connect_local = current_playback["device"]["id"] == self.playerid
                                            TypeError: 'NoneType' object has no attribute '__getitem__'
                                            -->End of Python script error report<--

**Comment by prometheanfire** [comment]
utils.py has `log_exc("Architecture detected. Using Spotty binary %s" % item)` instead of `log_exception`

**Comment by marcelveldt** [comment]
ok thanks was a bit in a hurry I guess

**Comment by prometheanfire** [comment]
on second thought, the log_exc was probably meant to be log_msg

**Comment by marcelveldt** [comment]
yep indeed

**Comment by marcelveldt** [comment]
just fixed it, now putting new version on the repo

**Comment by marcelveldt** [comment]
there will be yet another update later today because I have to rebuild the arm libraries for the connect feature

**Comment by marcelveldt** [comment]
but with this version playback will work again

**Comment by prometheanfire** [comment]
I'm running this on armhf now, with the latest version (14).

```
16:05:28.420 T:547381833952  NOTICE: plugin.audio.spotify --> Architecture detected. Using Spotty binary spotty-muslhf
16:05:28.424 T:547230839008  NOTICE: plugin.audio.spotify --> Audio proxy started on port 52308
16:05:29.294 T:547381833952  NOTICE: plugin.audio.spotify --> Retrieved auth token
16:05:29.860 T:547381833952  NOTICE: plugin.audio.spotify --> Logged in to Spotify - Username: mthode
16:05:29.892 T:545527951584  NOTICE: plugin.audio.spotify --> Start Spotify Connect Daemon
16:05:30.392 T:547381833952  NOTICE: plugin.audio.spotify --> waiting for playerid
16:06:44.974 T:545474498784  NOTICE: plugin.audio.spotify --> Playback requested for track 5ghMfHMHakVS0omjj2cBSA
                                              File "/storage/.kodi/addons/plugin.audio.spotify/resources/lib/player_monitor.py", line 49, in onPlayBackStarted
16:07:09.024 T:546465640672  NOTICE: plugin.audio.spotify --> Playback requested for track 56C7rBk3rrZ0bsm029Esw0
                                              File "/storage/.kodi/addons/plugin.audio.spotify/resources/lib/player_monitor.py", line 49, in onPlayBackStarted
```

Looks like the backtrace was fixed by fixing the log_msg thing, working other than that I think, not sure about the line 49 thing still.

Do you know if there's a shuffle play that works?

**Comment by marcelveldt** [comment]
shuffle is controlled by kodi

**Comment by marcelveldt** [comment]
if you're using local playback, the entire playlist is handled by kodi and all kodi controls apply...

**Comment by marcelveldt** [comment]
btw may I ask on what platform you're running the addon ? raspberry Pi ? OS ?

**Comment by prometheanfire** [comment]
thanks, and I'm on the odroid-c2

**Comment by prometheanfire** [comment]
libreelec 8.0.2

**Comment by marcelveldt** [comment]
ok thanks
