### ISSUE TITLE
Authentication/Authorization problems on libreelec

### ISSUE THREAD

**Issue by mklemenz** [marcelveldt/plugin.audio.spotify#28]
A dialog keeps popping up saying:
"The default browser should now be opened, follow the directions to authorize this app on Spotify"

... which is a bit hard on LibreElec 8.0.2 (Raspberry Pi 3)
when looking into the logs, it keeps repeating "Waiting for authentication token...", although all this might probably just be a symptom covering an earlier error, also seen in the logs.

Here's a grep on spotify from kodi.log:
```
10:21:40.142 T:1725952928  NOTICE: plugin.audio.spotify --> Architecture detected. Using librespot binary /storage/.kodi/addons/plugin.audio.spotify/resources/lib/librespot/linux_arm/librespot
10:21:40.142 T:1725952928  NOTICE: plugin.audio.spotify --> /storage/.kodi/addons/plugin.audio.spotify/resources/lib/librespot/linux_arm/librespot: error while loading shared libraries: /storage/.kodi/addons/plugin.audio.spotify/resources/lib/librespot/linux_arm/libasound.so.2: internal error
10:21:40.142 T:1725952928  NOTICE: plugin.audio.spotify --> Error while verifying librespot. Local playback is disabled.
10:21:40.152 T:1696748448  NOTICE: plugin.audio.spotify --> Audio proxy started on port 52308
10:24:13.821 T:1725952928  NOTICE: plugin.audio.spotify --> Launching system-default browser
10:24:13.821 T:1725952928  NOTICE: plugin.audio.spotify --> Waiting for authentication token...
10:24:41.830 T:1725952928  NOTICE: plugin.audio.spotify --> Waiting for authentication token...
10:25:11.839 T:1725952928  NOTICE: plugin.audio.spotify --> Waiting for authentication token...
10:25:41.848 T:1725952928  NOTICE: plugin.audio.spotify --> Waiting for authentication token...
10:25:43.848 T:1725952928  NOTICE: plugin.audio.spotify --> Waiting for authentication token...
```

This must have occured some time after version 1.1.16

**Comment by fportegies** [comment]
Thanks for the great add-on!
I have the same problem on libreelec.
Changed back to version 1.0.26.

**Comment by marcelveldt** [comment]
@mklemenz thanks for the report, I will have a look. 

@fportegies: What Libreelec version, which hardware are you using ?

**Comment by fportegies** [comment]
Raspberry pi 3
Libreelec 8.02
Kodi 17.3

Problem is a missing webbrowser to authenticate, I think.


Op 15 jun. 2017 11:34 schreef "Marcel van der Veldt" <
notifications@github.com>:

@mklemenz <https://github.com/mklemenz> thanks for the report, I will have
a look.

@fportegies <https://github.com/fportegies>: What Libreelec version, which
hardware are you using ?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/marcelveldt/plugin.audio.spotify/issues/28#issuecomment-308680880>,
or mute the thread

**Comment by marcelveldt** [comment]
No, it shouldn't ask for a webbrowser at all, that is only needed on Android or iOS.
It's failing to load librespot. Just created a small fix for that. I will put version 1.1.21 on the repo, can you give it a test drive ?

**Comment by fportegies** [comment]
That's fine!

Op 15 jun. 2017 11:40 schreef "Marcel van der Veldt" <
notifications@github.com>:

**Comment by mklemenz** [comment]
looks great, the fix works :)

**Comment by marcelveldt** [comment]
OK, great the fix works. I will have to improve it further in the future though because this code will crash on a Raspberry Pi 1 or Zero as that doesn't have HF support but for now it's fixed for Pi 2/3 users.

**Comment by fportegies** [comment]
It also works here 
Thanks for the quick respons.

**Comment by marcelveldt** [comment]
great !
