### ISSUE TITLE
Possible Kodi 17 issues?

### ISSUE THREAD

**Issue by im85288** [marcelveldt/plugin.audio.spotify#3]
I installed this for the first time with kodi v17 alpha 3 on windows and always get a failed to login message when attempting to access the addon.

The log shows a few failed attempts such as

`11:53:53 T:3816  NOTICE: Spotify --> Your platform (x86_64 System.Platform.Windows)
11:53:53 T:3816  NOTICE: Spotify --> Service already running
11:53:54 T:6416  NOTICE: Spotify --> Spotify Callbacks: 10:53:54.096 E [ap:1694] AP Socket Error: No connection could be made because the target machine actively refused it.  (10061)
11:53:54 T:6416   ERROR: None
11:53:54 T:6416  NOTICE: Spotify --> Spotify Callbacks: 10:53:54.096 E [ap:3915] Connection error:  101
11:53:54 T:6416   ERROR: None
11:53:54 T:6416  NOTICE: Spotify --> Spotify Callbacks: 10:53:54.096 I [ap:1752] Connecting to AP ap.gslb.spotify.com:80
11:53:54 T:3556  NOTICE: Spotify --> waiting for service...
11:53:54 T:6416  NOTICE: Spotify --> Spotify Callbacks: 10:53:54.213 I [ap:1226] Connected to AP: 74.208.238.62:80
11:53:54 T:6416  NOTICE: Spotify --> Spotify Callbacks: 10:53:54.345 E [ap:1694] AP Socket Error: Connection closed by peer (10053)
11:53:54 T:6416   ERROR: None
11:53:54 T:6416  NOTICE: Spotify --> Spotify Callbacks: 10:53:54.346 E [ap:3915] Connection error:  112`

I'm not sure at this stage if it is a kodi v17 issue or something else as this is the first install. On initial install it directed me to a web page where I authorised the kodi addon.

If there's any other info I can provide to help troubleshoot please let me know.

**Comment by marcelveldt** [comment]
This issue is that your machine wasn't able to connect to the spotify servers. Are you using a firewall or proxy ?

BTW: Kodi Krypton is still not compatible with this addon:

http://forum.kodi.tv/showthread.php?tid=278536&pid=2397498#pid2397498

**Comment by im85288** [comment]
Thanks for the link, when I first tried I was not aware the addon did not work in krypton. All working great on Jarvis so feel free to close the issue. Hopefully the kodi team looks into your thread as it would be a great loss to not have this working when krypton goes live.

**Comment by marcelveldt** [comment]
OK, great.
Yeah, something did definitely change in Krypton because it completely broke the addon.
I have been debugging the internal proxy to spotify for days and can only conclude it's in Kodi's code somewhere.
