### ISSUE TITLE
Sometimes Plays

### ISSUE THREAD

**Issue by sunnythaper** [marcelveldt/plugin.audio.spotify#30]
I can't quite narrow down the cause but it seems like your plugin works for me when searching for a song but playing playlists or even using Spotify on my laptop ends in a "One or more items failed to play" error. I am using 1.1.27 and am using a fresh install of OSMC.

**Comment by marcelveldt** [comment]
kodi logfile ?

**Comment by sunnythaper** [comment]
`01:46:53.096 T:1727001584  NOTICE: plugin.audio.spotify --> reported architecture: armv7l
01:46:53.109 T:1727001584  NOTICE: plugin.audio.spotify --> Architecture detected. Using librespot binary /home/osmc/.kodi/addons/plugin.audio.spotify/resources/lib/librespot/linux_armhf/librespot
01:46:54.990 T:1727001584  NOTICE: plugin.audio.spotify --> Available Backends : 
                                            - alsa (default)
                                            - pipe
01:46:55.154 T:1503654896  NOTICE: Skin Helper Service --> WebService - start helper webservice on port 52307
01:46:55.156 T:1743778800  NOTICE: Skin Helper Service --> Skin Helper Service version 1.1.3 started
01:46:57.883 T:1727001584  NOTICE: plugin.audio.spotify --> started webproxy at port 52308
01:46:58.310 T:1735390192  NOTICE: NEXTUP SERVICE NOTIFICATION Service -> Starting NextUp Service
01:46:58.341 T:1735390192  NOTICE: NEXTUP SERVICE NOTIFICATION Service -> ========  START NEXTUP SERVICE NOTIFICATION  ========
01:46:58.455 T:1735390192  NOTICE: NEXTUP SERVICE NOTIFICATION Service -> KODI Version: 17.3
01:46:58.455 T:1735390192  NOTICE: NEXTUP SERVICE NOTIFICATION Service -> NEXTUP SERVICE NOTIFICATION Version: 1.0.35
01:47:00.305 T:1752167408 WARNING: CSkinInfo: failed to load skin settings
01:47:04.546 T:1727001584  NOTICE: plugin.audio.spotify --> Retrieved auth token
01:47:05.239 T:1727001584  NOTICE: plugin.audio.spotify --> Logged in to Spotify - Username: sunnythaper
01:47:05.240 T:1701311472  NOTICE: plugin.audio.spotify --> Start Spotify Connect Daemon
01:47:26.401 T:1937765360   ERROR: Unable to find plugin
01:47:26.401 T:1958719488   ERROR: GetDirectory - Error getting plugin://
01:47:26.402 T:1958719488   ERROR: CGUIMediaWindow::GetDirectory(plugin://) failed
01:48:57.423 T:1958719488   ERROR: CCurlFile::FillBuffer - Failed: Timeout was reached(28)
01:48:57.423 T:1958719488   ERROR: CCurlFile::Open failed with code 0 for http://127.0.0.1:52308/track/4fS4hGJcIydMZrWo68DFMf/257
01:48:57.423 T:1958719488   ERROR: Open - failed to open source <http://127.0.0.1:52308/track/4fS4hGJcIydMZrWo68DFMf/257>
01:48:57.423 T:1958719488   ERROR: Init: Error opening file http://127.0.0.1:52308/track/4fS4hGJcIydMZrWo68DFMf/257
01:48:57.423 T:1958719488   ERROR: CAudioDecoder: Unable to Init Codec while loading file http://127.0.0.1:52308/track/4fS4hGJcIydMZrWo68DFMf/257
01:48:57.424 T:1958719488 WARNING: PAPlayer::QueueNextFileEx - Failed to create the decoder
01:48:57.424 T:1958719488   ERROR: Playlist Player: skipping unplayable item: 0, path [http://127.0.0.1:52308/track/4fS4hGJcIydMZrWo68DFMf/257]
01:49:04.067 T:1701311472  NOTICE: plugin.audio.spotify --> Connect player preloaded track 3C4fc2KMJg2cZxZNSO5jJK
01:49:09.870 T:1701311472  NOTICE: plugin.audio.spotify --> Connect player preloaded track 5fMTeldnScAK9IksdMHXPz
01:49:39.054 T:1701311472  NOTICE: plugin.audio.spotify --> Connect player preloaded track 2py2zs05jAULXnOG2hoazG
01:49:45.484 T:1701311472  NOTICE: plugin.audio.spotify --> Seek to 0 seconds requested by connect player
01:49:45.485 T:1701311472   ERROR: EXCEPTION: XBMC is not playing any media file
01:49:45.493 T:1701311472   ERROR: Exception in thread Thread-1:
                                            Traceback (most recent call last):
                                              File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
                                                self.run()
                                              File "/home/osmc/.kodi/addons/plugin.audio.spotify/resources/lib/main_service.py", line 228, in run
                                                self.__kodiplayer.seekTime(seek_sec)
                                            RuntimeError: XBMC is not playing any media file

---------------------- Kodi Old Log END --------------- 2qaAc90c
`

**Comment by marcelveldt** [comment]
Please test again with the latest version (1.1.35 or higher). Should work correctly now.
