### ISSUE TITLE
Doesn't work on kodi 17.3

### ISSUE THREAD

**Issue by tug912** [marcelveldt/plugin.audio.spotify#32]
Hi, and thanks for your work but i just tried it and doesn't seems to work. 
Tried it on Kodi 17.3 on PC and OSMC raspberry too.

**Comment by marcelveldt** [comment]
IT would help of you add a problem description and your Kodi log file

**Comment by tug912** [comment]
Hi, here is the log file : 

17:13:14.362 T:6992   ERROR: Control 50 in window 10502 has been asked to focus, but it can't
17:13:18.196 T:5636   ERROR: Unable to find plugin
17:13:18.196 T:6992   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://
17:13:18.196 T:6992   ERROR: CGUIMediaWindow::GetDirectory(plugin://) failed
17:13:38.650 T:6992   ERROR: CCurlFile::FillBuffer - Failed: Timeout was reached(28)
17:13:38.650 T:6992   ERROR: CCurlFile::Open failed with code 0 for http://localhost:52308/track/6VmBgpdYXbCXQ4eNA6KKDt/196
17:13:38.650 T:6992   ERROR: XFILE::CFileCache::Open - failed to open source <http://localhost:52308/track/6VmBgpdYXbCXQ4eNA6KKDt/196>
17:13:38.650 T:6992   ERROR: VideoPlayerCodec::Init: Error opening file http://localhost:52308/track/6VmBgpdYXbCXQ4eNA6KKDt/196
17:13:38.650 T:6992   ERROR: CAudioDecoder: Unable to Init Codec while loading file http://localhost:52308/track/6VmBgpdYXbCXQ4eNA6KKDt/196
17:13:38.650 T:6992 WARNING: PAPlayer::QueueNextFileEx - Failed to create the decoder
17:13:38.650 T:6992   ERROR: Playlist Player: skipping unplayable item: 0, path [http://localhost:52308/track/6VmBgpdYXbCXQ4eNA6KKDt/196]
17:13:48.734 T:6992   ERROR: CCurlFile::FillBuffer - Failed: Timeout was reached(28)
17:13:48.734 T:6992   ERROR: CCurlFile::Open failed with code 0 for http://localhost:52308/track/3y29QLWHxB1G7CfuFyZ8qe/448
17:13:48.734 T:6992   ERROR: XFILE::CFileCache::Open - failed to open source <http://localhost:52308/track/3y29QLWHxB1G7CfuFyZ8qe/448>
17:13:48.734 T:6992   ERROR: VideoPlayerCodec::Init: Error opening file http://localhost:52308/track/3y29QLWHxB1G7CfuFyZ8qe/448
17:13:48.734 T:6992   ERROR: CAudioDecoder: Unable to Init Codec while loading file http://localhost:52308/track/3y29QLWHxB1G7CfuFyZ8qe/448
17:13:48.734 T:6992 WARNING: PAPlayer::QueueNextFileEx - Failed to create the decoder
17:13:48.734 T:6992   ERROR: Playlist Player: skipping unplayable item: 1, path [http://localhost:52308/track/3y29QLWHxB1G7CfuFyZ8qe/448]
17:14:36.642 T:6992   ERROR: CCurlFile::FillBuffer - Failed: Timeout was reached(28)
17:14:36.642 T:6992   ERROR: CCurlFile::Open failed with code 0 for http://localhost:52308/track/37EhtXScazq7PJtpc9a8W1/177
17:14:36.642 T:6992   ERROR: XFILE::CFileCache::Open - failed to open source <http://localhost:52308/track/37EhtXScazq7PJtpc9a8W1/177>
17:14:36.642 T:6992   ERROR: VideoPlayerCodec::Init: Error opening file http://localhost:52308/track/37EhtXScazq7PJtpc9a8W1/177
17:14:36.642 T:6992   ERROR: CAudioDecoder: Unable to Init Codec while loading file http://localhost:52308/track/37EhtXScazq7PJtpc9a8W1/177
17:14:36.642 T:6992 WARNING: PAPlayer::QueueNextFileEx - Failed to create the decoder
17:14:36.642 T:6992   ERROR: Playlist Player: skipping unplayable item: 2, path [http://localhost:52308/track/37EhtXScazq7PJtpc9a8W1/177]
17:14:46.725 T:6992   ERROR: CCurlFile::FillBuffer - Failed: Timeout was reached(28)
17:14:46.725 T:6992   ERROR: CCurlFile::Open failed with code 0 for http://localhost:52308/track/6CTG85NJI1Wm60pxTSRNwL/234
17:14:46.725 T:6992   ERROR: XFILE::CFileCache::Open - failed to open source <http://localhost:52308/track/6CTG85NJI1Wm60pxTSRNwL/234>
17:14:46.725 T:6992   ERROR: VideoPlayerCodec::Init: Error opening file http://localhost:52308/track/6CTG85NJI1Wm60pxTSRNwL/234
17:14:46.725 T:6992   ERROR: CAudioDecoder: Unable to Init Codec while loading file http://localhost:52308/track/6CTG85NJI1Wm60pxTSRNwL/234
17:14:46.725 T:6992 WARNING: PAPlayer::QueueNextFileEx - Failed to create the decoder
17:14:46.725 T:6992   ERROR: Playlist Player: skipping unplayable item: 3, path [http://localhost:52308/track/6CTG85NJI1Wm60pxTSRNwL/234]

**Comment by tug912** [comment]
Sometimes it works i can play 1 or 2 songs but when i close the addon and try again it doesn't work.

**Comment by marcelveldt** [comment]
full debug logfile please, not just a snippet.

The issue you're experiencing if a known issue which I am investigating.
As a workaround, you may want to set the Connect player to directly output to the sound card and set the connect player as the active player.

That way Kodi is bypassed for playing the audio which will work more reliable. I have to discuss the issue with the Kodi team if I can solve the other issue.

**Comment by marcelveldt** [comment]
Please test again with version 1.1.36. The issues should be resolved.
