### ISSUE TITLE
Multi user switch only works twice

### ISSUE THREAD

**Issue by Rouzax** [marcelveldt/plugin.audio.spotify#33]
I love this plugin and would very much like to be able to switch Spotify accounts on our Kodi instance. Currently it does not work consistently, after switching twice it crashes.
System info:
Windows 10
Kodi 17.3
Plugin 1.1.29

Kodi Debug Log:
https://pastebin.com/8PXQRqE7

**Comment by marcelveldt** [comment]
I will provide a new version later today in which this should be fixed

**Comment by Rouzax** [comment]
Awesome

**Comment by Rouzax** [comment]
I've tested the new plugin from the repo and it seems a bit better but it is still hit and miss with connecting. From the thread I understand that there is an issue you are looking into to try and solve. 
Let me know if and what you need from me.

**Comment by marcelveldt** [comment]
Can you please test again with version 1.1.34 that is now available on my repo ?
If it's still failing, please provide me a full Kodi logfile after you tried to switch users a couple of times.
Thanks!

**Comment by Rouzax** [comment]
@marcelveldt The user switching is working great now however it seems that there are now some other issues.
When Playback device: `Local playback on this device` is selected a song will start but there will be no audio in Kodi.
If I select `Spotify Connect: Kodi (HTPC1)` it will actually play music but no matter how I start the album or list it will only play one song and than stop.
Do you want me to create a new ticket for that or add logging to this ticket?
