### ISSUE TITLE
Playback fails about 50% of the time from spotify connect

### ISSUE THREAD

**Issue by FilipLigaarden** [marcelveldt/plugin.audio.spotify#36]
Great work.
Setup:
Odroid C2
Libreelec V8.0.2
Plugins enabled: Twitch, Youtube, NRK, Spotify
Spotify connect from Oneplus3

Behavior: Playing a single track works about 50% of the time. This is the log from when it crashed. 
I have had this plugin installed for a few month and it has not been working until i tried it a few days ago when i saw the spotify connect player.
For it to start working i cleared everything belonging to this plugin.
Some times kodi freezes for a half a minute or so, and rarely it freezes entirely and a hard reset is needed. 
A playback failed error message pops up sometimes.

Also notable: 
After some time playback stops working entirely and a reboot helps.

If requested i will post a debug log where i spam commands (skipping, seeking etc).

Debug log:
`22:03:46.755 T:546459087072  NOTICE: plugin.audio.spotify --> Available Backends : 
                                            - alsa (default)
                                            - pipe
22:03:46.941 T:546425532640   DEBUG: UpdateMenuLanguage - using TV menu language is disabled
19:05:23.278 T:546459087072  NOTICE: plugin.audio.spotify --> started webproxy at port 52308
19:05:23.283 T:546891251936  NOTICE: Twitch: Service: Start
19:05:23.283 T:546891251936   DEBUG: Twitch: Player: Start
19:05:23.662 T:546433921248    INFO: ## LibreELEC Addon ## system::set_hostname ## LibreELEC
19:05:23.664 T:546433921248    INFO: ## LibreELEC Addon ## system::set_keyboard_layout ## us
19:05:23.664 T:546433921248    INFO: ## LibreELEC Addon ## system::set_keyboard_layout ## loadkmap < `ls -1 /usr/lib/keymaps/*/us.bmap`
19:05:23.736 T:546433921248    INFO: ## LibreELEC Addon ## system::updateThread ## Started
19:05:23.737 T:546433921248    INFO: ## LibreELEC Addon ## system::set_auto_update ## manual
19:05:23.783 T:545133687008    INFO: ## LibreELEC Addon ## _service_::run ## WAITING:
19:05:23.812 T:545142075616    INFO: ## LibreELEC Addon ## xdbus Monitor started. ##
19:05:24.027 T:546459087072   DEBUG: plugin.audio.spotify --> {"accessToken":"***","expiresIn":3600,"tokenType":"Bearer","scope":["playlist-read-private","playlist-read-collaborative","user-follow-read","playlist-modify-private","user-read-email","user-read-private","user-modify-playback-state","user-follow-modify","user-library-read","user-library-modify","playlist-modify-public","user-read-playback-state","user-read-currently-playing","user-read-birthdate","user-top-read"]}
19:05:24.028 T:546459087072   DEBUG: plugin.audio.spotify --> Token from librespot: {'access_token': '***', 'expires_in': 3600, 'expires_at': 1499025924, 'token_type': 'Bearer', 'scope': 'playlist-read-private playlist-read-collaborative user-follow-read playlist-modify-private user-read-email user-read-private user-modify-playback-state user-follow-modify user-library-read user-library-modify playlist-modify-public user-read-playback-state user-read-currently-playing user-read-birthdate user-top-read', 'refresh_token': '***'}
19:05:24.028 T:546459087072  NOTICE: plugin.audio.spotify --> Retrieved auth token
19:05:24.414 T:546459087072  NOTICE: plugin.audio.spotify --> Logged in to Spotify - Username: 1156860848
19:05:24.415 T:546459087072   DEBUG: plugin.audio.spotify --> Userdetails: {u'product': u'premium', u'display_name': u'nope', u'external_urls': {u'spotify': u'https://open.spotify.com/user/1156860848'}, u'country': u'NO', u'uri': u'spotify:user:****', u'birthdate': u'***', u'id': u'***', u'href': u'https://api.spotify.com/v1/users/1156860848', u'followers': {u'total': 6, u'href': None}, u'images': [{u'url': u'https://scontent.xx.fbcdn.net/v/t1.0-1/s200x200/1234382_10200466451319952_689132794_n.jpg?oh=66f64c11d2120337f16ee245ef6fad4e&oe=5A0FDE2A', u'width': None, u'height': None}], u'type': u'user', u'email': u'nope'}
19:05:24.415 T:545058189536  NOTICE: plugin.audio.spotify --> Start Spotify Connect Daemon
19:05:24.447 T:545058189536   DEBUG: plugin.audio.spotify --> INFO:librespot: librespot  (). Built on 2017-06-14.
19:05:24.508 T:545058189536   DEBUG: plugin.audio.spotify --> *** WARNING *** The program 'librespot' uses the Apple Bonjour compatibility layer of Avahi.
19:05:24.508 T:545058189536   DEBUG: plugin.audio.spotify --> *** WARNING *** Please fix your application to use the native API of Avahi!
19:05:24.509 T:545058189536   DEBUG: plugin.audio.spotify --> *** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=librespot>
19:05:24.634 T:545058189536   DEBUG: plugin.audio.spotify --> INFO:librespot::session: Connecting to AP "gew1-accesspoint-b-dz71.ap.spotify.com:4070"
19:05:25.024 T:545058189536   DEBUG: plugin.audio.spotify --> INFO:librespot::session: Authenticated as "1156860848" !
19:05:25.025 T:545058189536   DEBUG: plugin.audio.spotify --> DEBUG:librespot::session: new Session[0]
19:05:25.025 T:545058189536   DEBUG: plugin.audio.spotify --> DEBUG:librespot::spirc: new Spirc[0]
19:05:25.025 T:545058189536   DEBUG: plugin.audio.spotify --> DEBUG:librespot::player: new Player[0]
19:05:25.025 T:545058189536   DEBUG: plugin.audio.spotify --> DEBUG:librespot::mercury: new MercuryManager
19:05:25.025 T:545058189536   DEBUG: plugin.audio.spotify --> DEBUG:librespot::session: Session[0] strong=3 weak=2
19:05:25.025 T:545058189536   DEBUG: plugin.audio.spotify --> INFO:librespot::session: Country: "NO"
19:05:25.114 T:545058189536   DEBUG: plugin.audio.spotify --> DEBUG:librespot::mercury: subscribed uri=hm://remote/3/user/1156860848/ count=0
19:05:25.199 T:545058189536   DEBUG: plugin.audio.spotify --> DEBUG:librespot::spirc: kMessageTypeHello "Kodi (LibreELEC)" c18c9678c9166d23fea7e2ea42763474ef026717 1 1499022325025
19:05:25.199 T:545058189536   DEBUG: plugin.audio.spotify --> DEBUG:librespot::spirc: kMessageTypeNotify "webapi" webapi 78739489 0
19:05:25.322 T:545058189536   DEBUG: plugin.audio.spotify --> DEBUG:librespot::spirc: kMessageTypeNotify "ONEPLUS A3003" 1d3b637f4b2ee147e1222d7b9bb73a3d4a592550 1 1499022311936
19:05:25.416 T:545058189536   DEBUG: plugin.audio.spotify --> DEBUG:librespot::spirc: kMessageTypeNotify "ONEPLUS A3003" 1d3b637f4b2ee147e1222d7b9bb73a3d4a592550 29 1499022311936
19:05:25.520 T:545058189536   DEBUG: plugin.audio.spotify --> DEBUG:librespot::spirc: kMessageTypeNotify "Tyriveien" 5c5b1787b5771730cd8f012bb97a4c0184625688 425 1499022324612
19:05:27.785 T:547677523968   DEBUG: ------ Window Deinit (DialogNotification.xml) ------
19:05:27.921 T:546425532640   DEBUG: UpdateAudioSystemStatus - no CEC capable amplifier found
19:05:27.921 T:547677523968   DEBUG: ------ Window Init (DialogNotification.xml) ------
19:05:33.702 T:547677523968   DEBUG: ------ Window Deinit (DialogNotification.xml) ------
19:05:44.913 T:545058189536   DEBUG: plugin.audio.spotify --> DEBUG:librespot::spirc: kMessageTypeNotify "ONEPLUS A3003" 1d3b637f4b2ee147e1222d7b9bb73a3d4a592550 59 1499022343864
19:05:45.572 T:545058189536   DEBUG: plugin.audio.spotify --> DEBUG:librespot::spirc: kMessageTypeNotify "ONEPLUS A3003" 1d3b637f4b2ee147e1222d7b9bb73a3d4a592550 60 1499022344486
19:05:47.546 T:545058189536   DEBUG: plugin.audio.spotify --> DEBUG:librespot::spirc: kMessageTypeHello "ONEPLUS A3003" 1d3b637f4b2ee147e1222d7b9bb73a3d4a592550 61 1499022344486
19:05:47.593 T:545058189536   DEBUG: plugin.audio.spotify --> DEBUG:librespot::spirc: kMessageTypeNotify "webapi" webapi 78761869 0
19:05:47.721 T:545058189536   DEBUG: plugin.audio.spotify --> DEBUG:librespot::spirc: kMessageTypeNotify "Tyriveien" 5c5b1787b5771730cd8f012bb97a4c0184625688 426 1499022347022
19:05:47.796 T:545058189536   DEBUG: plugin.audio.spotify --> DEBUG:librespot::spirc: kMessageTypeNotify "ONEPLUS A3003" 1d3b637f4b2ee147e1222d7b9bb73a3d4a592550 30 1499022344486
19:05:47.847 T:545058189536   DEBUG: plugin.audio.spotify --> DEBUG:librespot::spirc: kMessageTypeNotify "Kodi (LibreELEC)" c18c9678c9166d23fea7e2ea42763474ef026717 2 1499022347546
19:05:51.748 T:545058189536   DEBUG: plugin.audio.spotify --> DEBUG:librespot::spirc: kMessageTypeLoad "ONEPLUS A3003" 1d3b637f4b2ee147e1222d7b9bb73a3d4a592550 2 0
19:05:51.748 T:545058189536   DEBUG: plugin.audio.spotify --> DEBUG:librespot::player: command=Load(SpotifyId(u128 { high: 8628615504486813098, low: 13666332449274282629 }), false, 553)
19:05:51.749 T:545058189536   DEBUG: plugin.audio.spotify --> DEBUG:librespot::metadata: new MetadataManager
19:05:51.985 T:545557901536   DEBUG: Thread JobWorker 545557901536 terminating (autodelete)
19:05:51.985 T:546450698464   DEBUG: Thread JobWorker 546450698464 terminating (autodelete)
19:05:51.987 T:546442309856   DEBUG: Thread JobWorker 546442309856 terminating (autodelete)
19:05:52.004 T:547660734688   DEBUG: Thread JobWorker 547660734688 terminating (autodelete)
19:05:52.261 T:547677511904   DEBUG: CAnnouncementManager - Announcement: OnAdd from xbmc
19:05:52.261 T:547677511904   DEBUG: GOT ANNOUNCEMENT, type: 2, from xbmc, message OnAdd
19:05:52.329 T:547677523968   DEBUG: Loading settings for http://localhost:52308/track/3DXncPQOG4VBw3QHh3S817/288
19:05:52.331 T:547677523968   DEBUG: CPlayerCoreFactory::GetPlayers(http://localhost:52308/track/3DXncPQOG4VBw3QHh3S817/288)
19:05:52.331 T:547677523968   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: system rules
19:05:52.331 T:547677523968   DEBUG: CPlayerSelectionRule::GetPlayers: matches rule: system rules
19:05:52.331 T:547677523968   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: mms/udp
19:05:52.331 T:547677523968   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: lastfm/shout
19:05:52.331 T:547677523968   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: rtmp
19:05:52.331 T:547677523968   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: rtsp
19:05:52.331 T:547677523968   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: streams
19:05:52.331 T:547677523968   DEBUG: CPlayerSelectionRule::GetPlayers: matches rule: streams
19:05:52.331 T:547677523968   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: aacp/sdp
19:05:52.331 T:547677523968   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: mp2
19:05:52.331 T:547677523968   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: dvd
19:05:52.331 T:547677523968   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: dvdimage
19:05:52.331 T:547677523968   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: sdp/asf
19:05:52.331 T:547677523968   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: nsv
19:05:52.331 T:547677523968   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: radio
19:05:52.331 T:547677523968   DEBUG: CPlayerCoreFactory::GetPlayers: matched 0 rules with players
19:05:52.331 T:547677523968   DEBUG: CPlayerCoreFactory::GetPlayers: adding audiodefaultplayer (PAPlayer)
19:05:52.331 T:547677523968   DEBUG: CPlayerCoreFactory::GetPlayers: for video=0, audio=1
19:05:52.331 T:547677523968   DEBUG: CPlayerCoreFactory::GetPlayers: for video=1, audio=1
19:05:52.331 T:547677523968   DEBUG: CPlayerCoreFactory::GetPlayers: adding player: VideoPlayer
19:05:52.331 T:547677523968   DEBUG: CPlayerCoreFactory::GetPlayers: added 2 players
19:05:52.332 T:547677523968   DEBUG: CFileCache::Open - opening <track/3DXncPQOG4VBw3QHh3S817/288> using cache
19:05:52.332 T:547677523968   DEBUG: CurlFile::Open(0x2ce8df0) http://localhost:52308/track/3DXncPQOG4VBw3QHh3S817/288
19:05:52.333 T:547677523968    INFO: easy_aquire - Created session to http://localhost
19:06:12.448 T:547677523968   ERROR: CCurlFile::FillBuffer - Failed: Timeout was reached(28)
19:06:12.448 T:547677523968   ERROR: CCurlFile::Open failed with code 0 for http://localhost:52308/track/3DXncPQOG4VBw3QHh3S817/288
19:06:12.448 T:547677523968   ERROR: Open - failed to open source <http://localhost:52308/track/3DXncPQOG4VBw3QHh3S817/288>
19:06:12.448 T:547677523968   ERROR: Init: Error opening file http://localhost:52308/track/3DXncPQOG4VBw3QHh3S817/288
19:06:12.448 T:547677523968   ERROR: CAudioDecoder: Unable to Init Codec while loading file http://localhost:52308/track/3DXncPQOG4VBw3QHh3S817/288
19:06:12.448 T:547677523968 WARNING: PAPlayer::QueueNextFileEx - Failed to create the decoder
19:06:12.448 T:547677523968   DEBUG: OnQueueNextItem: play state was 1, starting 1
19:06:12.448 T:547677523968   DEBUG: OnPlayBackStopped: play state was 1, starting 0
19:06:12.448 T:547677523968   ERROR: Playlist Player: skipping unplayable item: 0, path [http://localhost:52308/track/3DXncPQOG4VBw3QHh3S817/288]
19:06:12.448 T:547677523968   DEBUG: Playlist Player: one or more items failed to play... aborting playback
19:06:12.448 T:547677523968   DEBUG: ------ Window Init (DialogConfirm.xml) ------
19:06:12.448 T:547677523968    INFO: Loading skin file: DialogConfirm.xml, load type: KEEP_IN_MEMORY
19:06:12.456 T:547677511904   DEBUG: CAnnouncementManager - Announcement: OnStop from xbmc
19:06:12.456 T:547677511904   DEBUG: GOT ANNOUNCEMENT, type: 1, from xbmc, message OnStop
19:06:12.533 T:546891251936   DEBUG: Twitch: Player: |onPlayBackStopped|
19:06:15.378 T:546459087072  NOTICE: plugin.audio.spotify --> playback stopped`

**Comment by marcelveldt** [comment]
Please test again with version 1.1.34.
Also keep in mind that there is a fix pending for the Kodi code to make it 100% reliable.
