### ISSUE TITLE
Skipping track from spotify connect device fails

### ISSUE THREAD

**Issue by FilipLigaarden** [marcelveldt/plugin.audio.spotify#37]
When playing a track from a playlist works, skipping track from phone fails.
After a couple of times pressing play/pause the track starts playing.
This is not included in the log, as i assume it is related to #36 

`19:35:39.619 T:545058189536   DEBUG: plugin.audio.spotify --> DEBUG:librespot::spirc: kMessageTypeNext "ONEPLUS A3003" 1d3b637f4b2ee147e1222d7b9bb73a3d4a592550 16 0
19:35:39.670 T:545058189536   DEBUG: plugin.audio.spotify --> DEBUG:librespot::player: command=Load(SpotifyId(u128 { high: 10743718962674682985, low: 12442232790521455826 }), true, 0)
19:35:39.726 T:545058189536   DEBUG: plugin.audio.spotify --> DEBUG:librespot::spirc: kMessageTypeNotify "Kodi (LibreELEC)" c18c9678c9166d23fea7e2ea42763474ef026717 46 1499024139619
19:35:39.764 T:547677511904   DEBUG: CAnnouncementManager - Announcement: OnClear from xbmc
19:35:39.764 T:547677511904   DEBUG: GOT ANNOUNCEMENT, type: 2, from xbmc, message OnClear
19:35:40.649 T:547677511904   DEBUG: CAnnouncementManager - Announcement: OnAdd from xbmc
19:35:40.649 T:547677511904   DEBUG: GOT ANNOUNCEMENT, type: 2, from xbmc, message OnAdd
19:35:40.730 T:547677523968   DEBUG: DoWork - Saving file state for audio item http://localhost:52308/track/7FNyRafAkUgto3txPZhiO6/224
19:35:40.738 T:547677523968   DEBUG: Loading settings for http://localhost:52308/track/4xlrALxuaCf9yZBHJeTSG6/184
19:35:40.739 T:547677523968   DEBUG: CPlayerCoreFactory::GetPlayers(http://localhost:52308/track/4xlrALxuaCf9yZBHJeTSG6/184)
19:35:40.740 T:547677523968   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: system rules
19:35:40.740 T:547677523968   DEBUG: CPlayerSelectionRule::GetPlayers: matches rule: system rules
19:35:40.740 T:547677523968   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: mms/udp
19:35:40.740 T:547677523968   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: lastfm/shout
19:35:40.740 T:547677523968   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: rtmp
19:35:40.740 T:547677523968   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: rtsp
19:35:40.740 T:547677523968   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: streams
19:35:40.740 T:547677523968   DEBUG: CPlayerSelectionRule::GetPlayers: matches rule: streams
19:35:40.740 T:547677523968   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: aacp/sdp
19:35:40.740 T:547677523968   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: mp2
19:35:40.740 T:547677523968   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: dvd
19:35:40.740 T:547677523968   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: dvdimage
19:35:40.740 T:547677523968   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: sdp/asf
19:35:40.740 T:547677523968   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: nsv
19:35:40.740 T:547677523968   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: radio
19:35:40.740 T:547677523968   DEBUG: CPlayerCoreFactory::GetPlayers: matched 0 rules with players
19:35:40.740 T:547677523968   DEBUG: CPlayerCoreFactory::GetPlayers: adding audiodefaultplayer (PAPlayer)
19:35:40.740 T:547677523968   DEBUG: CPlayerCoreFactory::GetPlayers: for video=0, audio=1
19:35:40.740 T:547677523968   DEBUG: CPlayerCoreFactory::GetPlayers: for video=1, audio=1
19:35:40.740 T:547677523968   DEBUG: CPlayerCoreFactory::GetPlayers: adding player: VideoPlayer
19:35:40.740 T:547677523968   DEBUG: CPlayerCoreFactory::GetPlayers: added 2 players
19:35:40.741 T:547677511904   DEBUG: CAnnouncementManager - Announcement: OnSpeedChanged from xbmc
19:35:40.741 T:547677511904   DEBUG: GOT ANNOUNCEMENT, type: 1, from xbmc, message OnSpeedChanged
19:35:40.822 T:547646910688   DEBUG: CActiveAE::DiscardStream - audio stream deleted
19:35:40.822 T:547646910688   DEBUG: CActiveAE::ClearDiscardedBuffers - buffer pool deleted
19:35:40.823 T:547660734688   DEBUG: Previous line repeats 2 times.
19:35:40.823 T:547660734688   DEBUG: Thread FileCache 547660734688 terminating
19:35:40.830 T:545557901536   DEBUG: OnPlayBackStopped: play state was 2, starting 1
19:35:40.830 T:545557901536   DEBUG: Thread PAPlayer 545557901536 terminating
19:35:40.831 T:547677523968   DEBUG: CFileCache::Open - opening <track/4xlrALxuaCf9yZBHJeTSG6/184> using cache
19:35:40.831 T:547677523968   DEBUG: CurlFile::Open(0x5c47eb0) http://localhost:52308/track/4xlrALxuaCf9yZBHJeTSG6/184
19:35:43.823 T:547646910688   DEBUG: CActiveAE::ClearDiscardedBuffers - buffer pool deleted
19:35:52.044 T:546442309856   DEBUG: Thread JobWorker 546442309856 terminating (autodelete)
19:36:00.954 T:547677523968   ERROR: CCurlFile::FillBuffer - Failed: Timeout was reached(28)
19:36:00.954 T:547677523968   ERROR: CCurlFile::Open failed with code 0 for http://localhost:52308/track/4xlrALxuaCf9yZBHJeTSG6/184
19:36:00.954 T:547677523968   ERROR: Open - failed to open source <http://localhost:52308/track/4xlrALxuaCf9yZBHJeTSG6/184>
19:36:00.954 T:547677523968   ERROR: Init: Error opening file http://localhost:52308/track/4xlrALxuaCf9yZBHJeTSG6/184
19:36:00.954 T:547677523968   ERROR: CAudioDecoder: Unable to Init Codec while loading file http://localhost:52308/track/4xlrALxuaCf9yZBHJeTSG6/184
19:36:00.954 T:547677523968 WARNING: PAPlayer::QueueNextFileEx - Failed to create the decoder
19:36:00.954 T:547677523968   DEBUG: OnQueueNextItem: play state was 1, starting 1
19:36:00.954 T:547677523968   DEBUG: OnPlayBackStopped: play state was 1, starting 0
19:36:00.954 T:547677523968   ERROR: Playlist Player: skipping unplayable item: 0, path [http://localhost:52308/track/4xlrALxuaCf9yZBHJeTSG6/184]
19:36:00.954 T:547677523968   DEBUG: Playlist Player: one or more items failed to play... aborting playback
19:36:00.954 T:547677523968   DEBUG: ------ Window Init (DialogConfirm.xml) ------
19:36:00.960 T:547677511904   DEBUG: CAnnouncementManager - Announcement: OnStop from xbmc
19:36:00.960 T:547677511904   DEBUG: GOT ANNOUNCEMENT, type: 1, from xbmc, message OnStop
19:36:00.976 T:546891251936   DEBUG: Twitch: Player: |onPlayBackStopped|
19:36:01.117 T:546442309856   DEBUG: Thread JobWorker start, auto delete: true
19:36:01.117 T:546442309856   DEBUG: DoWork - Saving file state for audio item http://localhost:52308/track/7FNyRafAkUgto3txPZhiO6/224
19:36:01.117 T:547677523968   DEBUG: CDirectoryProvider[addons://sources/video/]: refreshing..
19:36:01.118 T:547677523968   DEBUG: CDirectoryProvider[addons://sources/audio/]: refreshing..
19:36:01.118 T:545557901536   DEBUG: Thread JobWorker start, auto delete: true
19:36:01.118 T:547677523968   DEBUG: CDirectoryProvider[addons://sources/executable/]: refreshing..
19:36:01.118 T:547677523968   DEBUG: CDirectoryProvider[addons://sources/image/]: refreshing..
19:36:01.118 T:547660734688   DEBUG: Thread JobWorker start, auto delete: true
19:36:01.282 T:546450698464   DEBUG: Previous line repeats 1 times.
19:36:01.282 T:546450698464   DEBUG: DoWork - took 152 ms to load special://masterprofile/Thumbnails/0/0ebce5ef.png
19:36:03.610 T:546459087072  NOTICE: plugin.audio.spotify --> playback stopped`

**Comment by marcelveldt** [comment]
Can you try this again please with version 1.1.34 ?
This should be fixed now.

BTW: there is still an issue within Kodi causing the playback to hang from time to time (lockup for 15 seconds, following a playback failed message). This will be fixed in the Kodi code soon:
https://github.com/xbmc/xbmc/pull/12504

**Comment by FilipLigaarden** [comment]
Works perfectly.
