### ISSUE TITLE
Can you add fanart to the Listitem

### ISSUE THREAD

**Issue by Ghawken** [marcelveldt/plugin.audio.spotify#38]
Thanks a lot for this plugin.

I have a secondary program that pulls the now playing info from Kodi and displays nowplaying type information.  I see that you don't get any fanart from spotify (from what I can tell on the images track).

If you can get fanart - could you set it as below - even a static Spotify fanart would be better than unset.  The other option would be to send the thumb as fanart to Kodi?  Saves a default screen and looks okay on my testing (does display twice - but better than default)

The fanart list item property is fanart_image.  And as used as setProperty

Eg, Such as adding the single line
li.setProperty('fanart_image', thumb)
to parse_spotify_track in utils.py

Thanks

`
```
def parse_spotify_track(track, is_album_track=True, silenced=False):
    if "track" in track:
        track = track['track']
    if track.get("images"):
        thumb = track["images"][0]['url']
    elif track['album'].get("images"):
        thumb = track['album']["images"][0]['url']
    else:
        thumb = ""
    duration = track['duration_ms']/1000
    
    if silenced:
        url = "http://localhost:%s/track/silence/%s" % (PROXY_PORT, duration)
    else:
        url = "http://localhost:%s/track/%s/%s" % (PROXY_PORT, track['id'], duration)

    li = xbmcgui.ListItem(
        track['name'],
        path=url,
        iconImage="DefaultMusicSongs.png",
        thumbnailImage=thumb
    )
	
    infolabels = {
        "title": track['name'],
        "genre": " / ".join(track["album"].get("genres", [])),
        "year": int(track["album"].get("release_date", "0").split("-")[0]),
        "album": track['album']["name"],
        "artist": " / ".join([artist["name"] for artist in track["artists"]]),
        "rating": str(get_track_rating(track["popularity"])),
        "duration": duration
    }
    if is_album_track:
        infolabels["tracknumber"] = track["track_number"]
        infolabels["discnumber"] = track["disc_number"]
    li.setInfo(type="Music", infoLabels=infolabels)
    li.setProperty("spotifytrackid", track['id'])
    li.setContentLookup(False)
    li.setProperty('do_not_analyze', 'true')
    li.setProperty('fanart_image',thumb)
    li.setMimeType("audio/wave")
    return url, li
```

**Comment by marcelveldt** [comment]
I'm sorry but a fan art image should be a fan art image, not just another image because there is no fan art. Besides the fact it will look awful, users will think there is something wrong.
If you want to show another image in your script, you can add this logic at your side right ?

That said, I'm planning on adding an option to the add-on to also fill the missing metadata.
Not only fan art but also discart etc.

**Comment by Ghawken** [comment]
Thanks.
I came to the same conclusion as well - and have changed it at my end.

But having fanart and cdArt would work even better

Look forward to it.

Thanks
