### ISSUE TITLE
show playlists achter search

### ISSUE THREAD

**Issue by fportegies** [marcelveldt/plugin.audio.spotify#42]
Hoi Marcel,

After search, I see the overview of amount of playlists found, but when I enter found playlists, I get an empty page, no results.

I use kodi 17.3 on libreelec 8.02 on rpi3.
I tried spotify 1.0.26 and 1.1.36.

Nothing special in logfile.

Groeten,
Frank

**Comment by fportegies** [comment]
Albums, Artists and Songs are displays OK

**Comment by fportegies** [comment]
Logfiles op http://sprunge.us/BMKR

**Comment by fportegies** [comment]
17:13:39.750 T:1961648128 WARNING: JSONRPC: Could not parse type "Setting.Details.SettingList" 17:13:40.282 T:1961648128 NOTICE: initialize done 17:13:40.282 T:1961648128 NOTICE: Running the application... 17:13:40.307 T:1961648128 NOTICE: starting zeroconf publishing 17:13:40.308 T:1961648128 NOTICE: CWebServer[8080]: Started 17:13:40.308 T:1961648128 NOTICE: starting upnp client 17:13:40.314 T:1961648128 NOTICE: starting upnp server 17:13:40.327 T:1515959200 NOTICE: ES: Starting UDP Event server on port 9777 17:13:40.328 T:1515959200 NOTICE: UDP: Listening on port 9777 (ipv6 : true) 17:13:41.514 T:1961648128 NOTICE: UDev: Added /var/media/TOSHIBA_EXT 17:13:42.362 T:1754264480 NOTICE: script.grab.fanart: Grab Fanart Service Started 17:13:43.369 T:1663615904 NOTICE: [plugin.video.youtube] Startup: detected Krypton (Kodi-17.3), setting DASH_SUPPORT_BUILTIN = False, DASH_SUPPORT_ADDON = True 17:13:43.805 T:1680393120 WARNING: CSkinInfo: failed to load skin settings 17:13:45.595 T:1873802144 WARNING: COMXImageFile::GetCodingType progressive images not supported by decoder 17:13:45.749 T:1440461728 WARNING: Previous line repeats 1 times. 17:13:45.749 T:1440461728 NOTICE: LoadJpeg: unable to load http://image.tmdb.org/t/p/original/4tfrTtBTT0Ih4yDONrxyjnA69mK.jpg 17:13:45.850 T:1873802144 WARNING: COMXImageFile::GetCodingType progressive images not supported by decoder 17:13:45.850 T:1873802144 NOTICE: LoadJpeg: unable to load http://image.tmdb.org/t/p/original/oXUWEc5i3wYyFnL1Ycu8ppxxPvs.jpg 17:13:45.865 T:1737487264 WARNING: COMXImageFile::GetCodingType progressive images not supported by decoder 17:13:45.867 T:1688781728 NOTICE: URLResolver: Initializing URLResolver version: 3.0.36 17:13:46.014 T:1729098656 WARNING: COMXImageFile::GetCodingType progressive images not supported by decoder 17:13:46.014 T:1729098656 NOTICE: LoadJpeg: unable to load http://image.tmdb.org/t/p/original/ilrZAV2klTB0FLxLb01bOp5pzD9.jpg 17:13:46.280 T:1737487264 WARNING: COMXImageFile::GetCodingType progressive images not supported by decoder 17:13:46.280 T:1737487264 NOTICE: LoadJpeg: unable to load http://image.tmdb.org/t/p/original/b7Dsaf7jOM7ZMRjlO8mn4su3RFi.jpg 17:13:46.411 T:1638450080 NOTICE: INDIGO NOTICE: STARTING INDIGO SERVICE 17:13:47.093 T:1873802144 WARNING: COMXImageFile::GetCodingType progressive images not supported by decoder 17:13:47.094 T:1873802144 NOTICE: LoadJpeg: unable to load http://image.tmdb.org/t/p/original/w6w8lbG8jajc7Y8AsDymZDfPw4u.jpg 17:13:47.402 T:1672004512 NOTICE: Common addon methods: Initializing addon.common version: 2.0.1 17:13:47.483 T:1688781728 NOTICE: Stream All The Sources: Service: Installed Version: 2.0.136 17:13:47.541 T:1630061472 NOTICE: VPN Mgr : (service.py) Starting VPN monitor service, platform is 2, version is 4.0.9 17:13:47.541 T:1630061472 NOTICE: VPN Mgr : (service.py) Kodi build is 17.3 Git:147cec4 17:13:47.541 T:1630061472 NOTICE: VPN Mgr : (service.py) Addon path is /storage/.kodi/addons/service.vpn.manager/ 17:13:47.696 T:1638450080 NOTICE: INDIGO NOTICE: Auto Main Turned off 17:13:47.696 T:1638450080 NOTICE: INDIGO NOTICE: SCRIPT BLOCKER ON 17:13:47.709 T:1672004512 NOTICE: 1Channel: Service: Installed Version: 2.5.72 17:13:47.805 T:1672004512 NOTICE: 1Channel: Loading sqlite3 as DB engine 17:13:47.811 T:1646838688 NOTICE: [SPECTO]: ->---------- PARAMS: {'action': 'service'} 17:13:47.847 T:1638450080 ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<-- - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS! Error Type: <class 'urllib2.URLError'> Error Contents: <urlopen error [Errno -2] Name or service not known> Traceback (most recent call last): File "/storage/.kodi/addons/plugin.program.indigo/service.py", line 78, in <module> support.scriptblock_checks() File "/storage/.kodi/addons/plugin.program.indigo/support.py", line 31, in scriptblock_checks response = urllib2.urlopen(req) File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen File "/usr/lib/python2.7/urllib2.py", line 429, in open File "/usr/lib/python2.7/urllib2.py", line 447, in _open File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain File "/usr/lib/python2.7/urllib2.py", line 1228, in http_open File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open URLError: <urlopen error [Errno -2] Name or service not known> -->End of Python script error report<-- 17:13:47.888 T:1672004512 NOTICE: 1Channel: Service: Resetting... 17:13:47.891 T:1672004512 NOTICE: 1Channel: Service: starting... 17:13:48.205 T:1688781728 NOTICE: Stream All The Sources: Service: starting... 17:13:49.297 T:1630061472 NOTICE: VPN Mgr : (service.py) Connecting to VPN profile /storage/.kodi/addons/service.vpn.manager/PIA/Netherlands (UDP).ovpn 17:13:59.530 T:1663615904 NOTICE: Spotify --> Your platform (armv7 System.Platform.Linux) 17:14:00.167 T:1663615904 NOTICE: Spotify --> Starting background service... 17:14:00.308 T:1663615904 NOTICE: Spotify --> Checking remembered_user .. 17:14:00.314 T:1663615904 NOTICE: Spotify --> Cached session found 17:14:00.324 T:1524347808 NOTICE: Spotify --> logged in: 0 17:14:05.574 T:1663615904 NOTICE: Spotify --> starting proxy at port 8090 17:14:05.574 T:1663615904 NOTICE: Spotify --> Setting callback .. 17:14:05.575 T:1663615904 NOTICE: Spotify --> Obtaining user token .. 17:14:05.575 T:1663615904 NOTICE: Spotify --> Encoding header .. 17:14:20.545 T:1183941536 ERROR: Window Translator: Can't find window musiclibrary 17:14:28.217 T:1158775712 WARNING: CSkinInfo: failed to load skin settings 17:14:28.275 T:1961648128 WARNING: Skin has invalid include: DefaultBackground 17:14:28.276 T:1961648128 WARNING: Skin has invalid include: TopBar 17:14:28.276 T:1961648128 WARNING: Skin has invalid include: BottomBar 17:14:28.284 T:1961648128 ERROR: Window Translator: Can't find window videolibrary 17:14:28.284 T:1961648128 WARNING: Label Formating: $VAR[GlobalFanartVar] is not defined 17:14:28.361 T:1961648128 ERROR: Control 1000 in window 13001 has been asked to focus, but it can't 17:14:28.373 T:1961648128 WARNING: COMXImageFile::GetCodingType progressive images not supported by decoder 17:14:28.373 T:1961648128 NOTICE: LoadJpeg: unable to load /usr/share/kodi/addons/service.libreelec.settings/resources/skins/Default/media/default/bg.jpg ======== /storage/.kodi/temp/dmesg.txt ==============

**Comment by marcelveldt** [comment]
Issue will be fixed in version 1.1.37. Thanks for reporting.
