### ISSUE TITLE
Spotify Connect stops after 1 song

### ISSUE THREAD

**Issue by Animizio** [marcelveldt/plugin.audio.spotify#43]
Hey,
i downloaded and tried your spotify Addon.
Using it through kodi works fine for me.
But when i want to use spotify Connect:
Opening spotify on my mobile, checking my kodi as play source and starting a song..it stops after the song is played and closes the kodi player.
I tried to start playlists, but its still the same..only 1 song played and player gets closed. When i click stop and play on my mobile, player opens again and plays a song..then agaon it stops..
Plesse fix this! Thank you very much! :)

**Comment by marcelveldt** [comment]
What version of the addon are you using ? Did you install it from my repo ?

**Comment by Animizio** [comment]
I m using the latest Version and yes i have your repo and installed it from it.

**Comment by Animizio** [comment]
To Name it: its Version 1.1.37

**Comment by marcelveldt** [comment]
OK, thanks, strange...
What OS/platform are you using ?

**Comment by Animizio** [comment]
I'm on a libreelec modification for s912 devices (Android Box T95Z Plus)

**Comment by Animizio** [comment]
https://forum.libreelec.tv/thread/5848-8-0-2e-libreelec-8-0-for-s912/

**Comment by Animizio** [comment]
Are you still working for a fix? :)

**Comment by marcelveldt** [comment]
please test with version 1.1.38 if it's fixed. If not, please provide me your kodi logfile after you've experienced the issue

**Comment by Animizio** [comment]
Tested...sadly still the same Problem

**Comment by Animizio** [comment]
Will create a logfile soon

**Comment by marcelveldt** [comment]
OK, it's working fine on my end on multiple machines so I'm curious about the log.

Hmmm, I spot one little detail in the code...

Can you try to start playback, skip to the next track manually and wait if it does continue the rest of the playlist ?

**Comment by Animizio** [comment]
Okay will test it and report

**Comment by Animizio** [comment]
Okay:
Starting a song works and plays it.
While playing i click next on my phone and it works -> next song is playing
Waitited till the song Ended and then -> wow...it plays the same song again...haha...but well that works..it plays.


Another info if this helps: 
cache is default, so activated.
Librespot is not working for me too..it has a lot oft problems switching from phone to the kodi device..most of the time it stops the connection..only sometimes it plays some music.
They are different problems, but i thoughed maybe it helps ya..

**Comment by Animizio** [comment]
But i started a playlist, not only the song :)

**Comment by Animizio** [comment]
Okay my Bad...maybe it was really only one song..started a playlist and it works...
But only when i click next when i first Start a song.

**Comment by Animizio** [comment]
So yes...i think you found the bug! Awesome work!!!

**Comment by marcelveldt** [comment]
OK, thanks for your help testing. I'll include a fix in the next update. Stupid bug. While I was testing my code I tested with skipping a track, never had the patience to wait until a full track was played :-)

**Comment by Animizio** [comment]
Hahaha what a joke :D
Well i m very happy, that its only a small bug which can get fixed easily :)
Ah well...playing spotify in kodi locally is buggy too for me..
The play or put to playlist does not working always..often i have to click multiple times there and there..until a song gets played.
So i m not really sure which button work or not..
Also most of the time..some songs never get played (for example..first song of a playlist, but second does). So its really unstable for me at least.

Again, thanks for every hard work you did there!

**Comment by Animizio** [comment]
When will be the next update out?

**Comment by marcelveldt** [comment]
the update was published. Did you had a chance to test it ?

**Comment by Animizio** [comment]
Yeah i got the .42 and actually it seems to work :) thank you
Will test it for a while and report back
