### ISSUE TITLE
Possibly bug with displaying playlist

### ISSUE THREAD

**Issue by yulrizka** [marcelveldt/plugin.audio.spotify#44]
https://github.com/marcelveldt/plugin.audio.spotify/commit/f527de94f4dba74d2fcdad28295e9e4ddd5cc0f7#diff-654d167e8cb2be0c6f08e8021ea08e97R1218

Is that correct? seems that the `label` params is not defined

**Comment by marcelveldt** [comment]
no, is typo, already fixed but I'll have to push to git
