### ISSUE TITLE
Add to Playlist

### ISSUE THREAD

**Issue by lionking15** [marcelveldt/plugin.audio.spotify#45]
Hi, Thank you for a great addon....Would it be possible to include "Add to Playlist", in the context menu of a song that is already in a playlist ?...The spotify on iPhone allows you to do this, which allows you to add a song from a playlist to another playlist, or create a new playlist where u can add that song to.

Once again, really appreaciate the addon

**Comment by marcelveldt** [comment]
Will be added in next version.

**Comment by lionking15** [comment]
That's great, Thank you :)
