### ISSUE TITLE
Cannot login

### ISSUE THREAD

**Issue by Satris404** [marcelveldt/plugin.audio.spotify#46]
Hi, 

the update didn't fix my problem (Previously Issu #34 ). I can't login on whatever operating system/machine. I tried to login with a US account but didn't do. My guess is that I can't login because I'm in Canada.

**Comment by marcelveldt** [comment]
Is there no Spotify in Canada ? The same rules apply as for the native Spotify apps. If the native app does not work in a specific region, this add-on will also not work.

**Comment by Satris404** [comment]
Yes there is. I just really don't know why I'm the only one for who this addon doesn't work.

**Comment by Satris404** [comment]
@marcelveldt  UPDATE - I finally succeeded to connect on my spotify account on my laptop. 
Unfortunately, I encountered more problems. Sometimes, when I select a folder, it shows up as empty. It's not a big problem as I can just reload and everything appears. But, what's more critical, is that I can't get a song to play. When I press a song, nothing happens.

**Comment by marcelveldt** [comment]
What did you do to make it work? And as for the other issues, I really need a Kodi logfile, grabbed right after you experienced the issues

**Comment by Satris404** [comment]
I just bought a new pc and thought it was a good idea to try it again. So I downloaded the ZIP from this github just to make sure it's the last version and I installed it. Actually, it's the first and only one addon installed in kodi on my new laptop right now. I'll have to test it out on my other devices. And yes sure, I'll send you the log file in not so long.

**Comment by Satris404** [comment]
Here's the log when a folder appears empty:

11:26:17.377 T:10736  NOTICE: plugin.audio.spotify --> Architecture detected. Using librespot binary C:\Users\Samuel\AppData\Roaming\Kodi\addons\plugin.audio.spotify\resources\lib\librespot\windows_x86_64\librespot.exe
11:26:17.430 T:10736  NOTICE: plugin.audio.spotify -->
11:26:17.430 T:10736  NOTICE: plugin.audio.spotify --> Error while verifying librespot. Local playback is disabled.
11:26:17.433 T:10736  NOTICE: plugin.audio.spotify --> started webproxy at port 52308
11:26:17.440 T:10736  NOTICE: plugin.audio.spotify --> Retrieved auth token
11:26:18.835 T:10736  NOTICE: plugin.audio.spotify --> Logged in to Spotify - Username: tremblaysam
11:26:36.934 T:4480   ERROR: XFILE::CDirectory::GetDirectory - Error getting
11:26:37.345 T:5516   ERROR: Previous line repeats 3 times.
11:26:37.345 T:5516 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(sources) in sources://music.tbn
11:28:13.348 T:11944 WARNING: Previous line repeats 1 times.
11:28:13.348 T:11944   ERROR: XFILE::CDirectory::GetDirectory - Error getting
11:28:53.701 T:11436   ERROR: Previous line repeats 6 times.
11:28:53.701 T:11436  NOTICE: My Music: Scanning for music info using worker thread, operation took 01:57
11:37:26.194 T:5516   ERROR: Control 55 in window 10502 has been asked to focus, but it can't
11:37:34.398 T:3736 WARNING: plugin.audio.spotify --> Exception in plugin_content ! --> 'NoneType' object has no attribute '__getitem__'
11:37:37.444 T:740   ERROR: Unable to find plugin
11:37:37.444 T:5516   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://
11:37:37.444 T:5516   ERROR: CGUIMediaWindow::GetDirectory(plugin://) failed
11:38:16.803 T:5516   ERROR: Control 55 in window 10502 has been asked to focus, but it can't
11:38:31.488 T:7660 WARNING: plugin.audio.spotify --> Exception in plugin_content ! --> 'NoneType' object has no attribute '__getitem__'

**Comment by Satris404** [comment]
more precisly this part:

11:55:36.054 T:5516   ERROR: Control 55 in window 10502 has been asked to focus, but it can't
11:55:46.717 T:5516   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.audio.spotify/?action=browse_newreleases
11:55:46.717 T:5516   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.audio.spotify/?action=browse_newreleases) failed
11:55:53.153 T:5516   ERROR: Control 55 in window 10502 has been asked to focus, but it can't
11:57:05.828 T:13752 WARNING: plugin.audio.spotify --> Exception in plugin_content ! --> 'NoneType' object has no attribute '__getitem__'

**Comment by Satris404** [comment]
this is when I try to play something: 

12:00:21.833 T:12324 WARNING: Attempt to use invalid handle -1
12:00:23.551 T:4936 WARNING: plugin.audio.spotify --> Exception in plugin_content ! --> http status: 403, code:-1 - https://api.spotify.com/v1/me/player/play:
                                             Not available for the current user
12:00:23.551 T:4936 WARNING: Attempt to use invalid handle -1
12:00:26.020 T:12300 WARNING: plugin.audio.spotify --> Exception in plugin_content ! --> http status: 403, code:-1 - https://api.spotify.com/v1/me/player/play:
                                             Not available for the current user
12:00:26.020 T:12300 WARNING: Attempt to use invalid handle -1
12:00:28.139 T:232 WARNING: plugin.audio.spotify --> Exception in plugin_content ! --> 'NoneType' object has no attribute '__getitem__'
12:00:28.139 T:232 WARNING: Attempt to use invalid handle -1

**Comment by Satris404** [comment]
Actually it is more complicated than that. I installed by error an old version of the spotify addon (1.1.29) on my laptop. When I tried to update the addon, it had a dependency error with script.module.cherrypy. I then installed the script.module.cherrypy module from the zip available on github and was able to install spotify correctly. But this brought more problem. Now, the spotify addon crashes recurrently (spotty_x64.exe has stopped working) and I cannot not login (as my old problem).  Here is the kodi log file:

19:34:11.974 T:11652   ERROR: XFILE::CDirectory::GetDirectory - Error getting
19:34:23.863 T:11652   ERROR: Previous line repeats 3 times.
19:34:23.863 T:11652   ERROR: Unable to find plugin
19:34:23.863 T:9472   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://
19:34:23.863 T:9472   ERROR: CGUIMediaWindow::GetDirectory(plugin://) failed
19:34:32.572 T:9472   ERROR: Control 55 in window 10502 has been asked to focus, but it can't
19:34:50.561 T:9472  NOTICE: Storing total System Uptime
19:34:50.563 T:9472  NOTICE: Saving settings
19:34:50.573 T:9472  NOTICE: Saving skin settings
19:34:50.578 T:9472  NOTICE: stop all
19:34:50.578 T:9472  NOTICE: stop player
19:34:50.578 T:9472  NOTICE: ES: Stopping event server
19:34:50.578 T:9472  NOTICE: stopping upnp
19:34:51.050 T:2804  NOTICE: ES: UDP Event server stopped
19:34:51.112 T:9472  NOTICE: clean cached files!
19:34:53.107 T:9664  NOTICE: plugin.audio.spotify --> Shutdown requested !
19:34:53.381 T:9664  NOTICE: plugin.audio.spotify --> stopped
19:34:56.125 T:9472   ERROR: CPythonInvoker(1, C:\Users\Samuel\AppData\Roaming\Kodi\addons\plugin.audio.spotify\service.py): script didn't stop in 5 seconds - let's kill it
19:34:56.125 T:9472  NOTICE: closing down remote control service
19:34:56.125 T:9472  NOTICE: stopped
19:34:56.328 T:9472  NOTICE: destroy
19:34:56.328 T:9472  NOTICE: unload skin
19:34:57.154 T:9472  NOTICE: unload sections
19:34:57.157 T:9472  NOTICE: special://profile/ is mapped to: special://masterprofile/
19:34:57.159 T:9472  NOTICE: application stopped...

**Comment by Satris404** [comment]
Moreover, I installed by curiosity the 1.1.29 version on my raspberry pi and it can't login with my credentials. One thing different thought, on my PC, I had to go through spotify website in order to authorize the kodi's spotify addon. But now, since I'm on my raspberry pi, it can't popup the internet browser (because there is none).

**Comment by marcelveldt** [comment]
Why don't you install the add-on the recommended way, by using my repo ?
That way, you make sure that all dependencies are satisfied. Besides that, it is in generic a very bad idea to just download the zip from git. Maybe I checked in some non tested stuff and besides that, the GitHub zip will prefix the folder so you end up with a mess in your kodi addons folder with all duplicated addons fighting with each other.

TIP: Install clean by using my repo.

Don't use the 1.0.29 version anymore, it's not supported anymore and it won't work on your pi. Use the 1.1.x version on my repo.

On your Windows machine: Install the MS Visual C++ runtime 2015

**Comment by Satris404** [comment]
Sorry about all that, you're right. I already had the repository installed on my raspberry but not on my pc. Even with your repository and everything updated, it crashes anyway. (btw, MS visual studio runtime C++ 2015 was already installed with the latest version) 

And about the raspberry pi, do I need to authorize the kodi addon to access my spotify account from the web browser as I had to do on my PC? Because there is no internet browser on my raspberry pi.

**Comment by marcelveldt** [comment]
Sorry for the late reply... Just to confirm... You are using a spotify PREMIUM account, right ?
