### ISSUE TITLE
Feature Request: Enable device to listen to all/multiple user connections

### ISSUE THREAD

**Issue by jnk22** [marcelveldt/plugin.audio.spotify#47]
Is it possible to add a feature, so one Kodi device acts as a "Spotify Connect" client for multiple users **at the same time**?

It was similiar to that a few weeks ago, where every Spotify user in your LAN was able to stream to that device, but now fixed as it obviously seemed to be some sort of a bug.

My idea for the settings menu:
- When activating "multiple user support", also enable the option to let the device listen to all the registered accounts
- Add an option to listen to ALL clients in your LAN. (Great for guests in your network)

**Comment by marcelveldt** [comment]
I get what you mean but currently it's not supported because I disabled the discovery mode as it was conflicting with the avahi dns service builtin Kodi. I did try to manually compile librespot with avahi support but that was too much work to make it compatible for all platforms.

Offcourse I will keep an eye out for a resolution.

**Comment by jnk22** [comment]
Thank you for your quick reply!
So it was more a feature than a bug a few weeks ago, didn't know about that.

If there is any testing about this I can help you with some time in the future, just let me know :)

**Comment by marcelveldt** [comment]
Yes it was a feature, it's the discovery feature of Spotify which will allow you to authenticate to a Spotify connect device using the spotify app. 
Because of the collision with the Kodi discovery I had to disable it for now.

**Comment by umfk** [comment]
@marcelveldt

**Comment by marcelveldt** [comment]
new version will be available on the repo within a few minutes, this contains the discovery mode by default.
