### ISSUE TITLE
Multiple users, switching not working

### ISSUE THREAD

**Issue by Clowting** [marcelveldt/plugin.audio.spotify#48]
I'm trying to use to multiple user functionality but it doesn't seem to work. A log file is included with the error line when pressing the "Current User" option. The main user is a Facebook user, the secondary user is a 'normal' Spotify user.

I use a Raspberry Pi 2 running the latest version of OSMC.
(Linux osmc 4.9.29-9-osmc #1 SMP PREEMPT Sat Jul 29 01:44:42 UTC 2017 armv7l GNU/Linux)

> 20:21:37.389 T:1498592240 WARNING: plugin.audio.spotify --> Exception in plugin_content ! --> http status: 400, code:-1 - https://api.spotify.com/v1/users/tclowting@gmail.com:
                                             Invalid username
20:21:37.389 T:1498592240 WARNING: Attempt to use invalid handle -1
20:21:59.360 T:1187222512 WARNING: plugin.audio.spotify --> Exception in plugin_content ! --> http status: 400, code:-1 - https://api.spotify.com/v1/users/tclowting@gmail.com:
                                             Invalid username
20:21:59.375 T:1187222512 WARNING: Attempt to use invalid handle -1
20:23:30.840 T:1700787184 WARNING: plugin.audio.spotify --> Exception in plugin_content ! --> http status: 400, code:-1 - https://api.spotify.com/v1/users/tclowting@gmail.com:
                                             Invalid username
20:23:30.840 T:1700787184 WARNING: Attempt to use invalid handle -1
20:23:38.373 T:1545597936 WARNING: plugin.audio.spotify --> Exception in plugin_content ! --> http status: 400, code:-1 - https://api.spotify.com/v1/users/tclowting@gmail.com:
                                             Invalid username
20:23:38.374 T:1545597936 WARNING: Attempt to use invalid handle -1
20:23:38.470 T:1187222512 WARNING: plugin.audio.spotify --> Exception in plugin_content ! --> http status: 400, code:-1 - https://api.spotify.com/v1/users/tclowting@gmail.com:
                                             Invalid username
20:23:38.470 T:1187222512 WARNING: Attempt to use invalid handle -1
20:23:38.545 T:1212937200 WARNING: plugin.audio.spotify --> Exception in plugin_content ! --> http status: 400, code:-1 - https://api.spotify.com/v1/users/tclowting@gmail.com:
                                             Invalid username
20:23:38.546 T:1212937200 WARNING: Attempt to use invalid handle -1
20:23:38.593 T:1498592240 WARNING: plugin.audio.spotify --> Exception in plugin_content ! --> http status: 400, code:-1 - https://api.spotify.com/v1/users/tclowting@gmail.com:
                                             Invalid username
20:23:38.593 T:1498592240 WARNING: Attempt to use invalid handle -1
20:25:01.758 T:1700787184 WARNING: plugin.audio.spotify --> Exception in plugin_content ! --> http status: 400, code:-1 - https://api.spotify.com/v1/users/tclowting@gmail.com:
                                             Invalid username
20:25:01.759 T:1700787184 WARNING: Attempt to use invalid handle -1
20:25:02.548 T:1742730224 WARNING: CSkinInfo: failed to load skin settings
20:25:02.794 T:1742730224   ERROR: EXCEPTION: Non-Existent Control 300
20:25:07.920 T:1228927984 WARNING: CPythonInvoker(27): Script invoked without an addon. Adding all addon modules installed to python path as fallback. This behaviour will be removed in future version.
20:28:17.103 T:1131672560 WARNING: plugin.audio.spotify --> Exception in plugin_content ! --> http status: 400, code:-1 - https://api.spotify.com/v1/users/tclowting@gmail.com:
                                             Invalid username
20:28:17.139 T:1959043072  NOTICE: VideoPlayer: Opening:
20:28:17.139 T:1959043072 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
20:28:17.141 T:1148711920  NOTICE: Creating InputStream
20:28:17.161 T:1148711920   ERROR: Error on dvdnav_open
20:28:17.161 T:1148711920   ERROR: CVideoPlayer::OpenInputStream - error opening []
20:28:17.161 T:1148711920  NOTICE: CVideoPlayer::OnExit()
20:28:17.162 T:1959043072   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.audio.spotify/?action=switch_user]
20:28:17.171 T:1959043072  NOTICE: CVideoPlayer::CloseFile()
20:28:17.172 T:1959043072  NOTICE: VideoPlayer: waiting for threads to exit
20:28:17.172 T:1959043072  NOTICE: VideoPlayer: finished waiting
20:28:17.172 T:1959043072  NOTICE: CVideoPlayer::CloseFile()
20:28:17.172 T:1959043072  NOTICE: VideoPlayer: waiting for threads to exit
20:28:17.172 T:1959043072  NOTICE: VideoPlayer: finished waiting
20:28:31.100 T:1123283952 WARNING: plugin.audio.spotify --> Exception in plugin_content ! --> http status: 400, code:-1 - https://api.spotify.com/v1/users/tclowting@gmail.com:
                                             Invalid username
20:28:31.136 T:1959043072  NOTICE: VideoPlayer: Opening:
20:28:31.136 T:1959043072 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
20:28:31.142 T:1114895344  NOTICE: Creating InputStream
20:28:31.145 T:1114895344   ERROR: Error on dvdnav_open
20:28:31.145 T:1114895344   ERROR: CVideoPlayer::OpenInputStream - error opening []
20:28:31.145 T:1114895344  NOTICE: CVideoPlayer::OnExit()
20:28:31.146 T:1959043072   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.audio.spotify/?action=switch_user]
20:28:31.153 T:1959043072  NOTICE: CVideoPlayer::CloseFile()
20:28:31.154 T:1959043072  NOTICE: VideoPlayer: waiting for threads to exit
20:28:31.154 T:1959043072  NOTICE: VideoPlayer: finished waiting
20:28:31.154 T:1959043072  NOTICE: CVideoPlayer::CloseFile()
20:28:31.154 T:1959043072  NOTICE: VideoPlayer: waiting for threads to exit
20:28:31.154 T:1959043072  NOTICE: VideoPlayer: finished waiting
20:29:04.157 T:1742730224 WARNING: CSkinInfo: failed to load skin settings
20:29:04.410 T:1742730224   ERROR: EXCEPTION: Non-Existent Control 300
20:29:09.379 T:1106506736 WARNING: CPythonInvoker(35): Script invoked without an addon. Adding all addon modules installed to python path as fallback. This behaviour will be removed in future version.

**Comment by marcelveldt** [comment]
You can't use your Facebook account directly... You will have to create a device account/password. You can do that in the spotify account details.

**Comment by Clowting** [comment]
Ah okay thanks, I didn't know about that. Strange enough the Facebook account does work when entering the normal credentials, it's just the switching doesn't seem to work. I'll try it with a device account/password this afternoon.

**Comment by Clowting** [comment]
This seems to fix my problem, thanks again! I'm not sure if I just missed it but maybe it's a good idea to add the fact that you have to create a device account/password somewhere in the main post on the Kodi forum for other noobs like me. 🤔
