### ISSUE TITLE
Stream with high quality

### ISSUE THREAD

**Issue by imbegoo** [marcelveldt/plugin.audio.spotify#49]
Hi there and thanks for the script! I'm using it on a rpi3-openelec. I'm a bit of a music nerd and I think that there should be an option to chose high quality streams. Is that posible to fix? Right now I think it's using the default quality but I can be wrong. Keep up the good work.

// Ola

**Comment by marcelveldt** [comment]
The quality is hardcoded to the highest bitrate.

**Comment by imbegoo** [comment]
Ah! Thanks for the answer and information. I thought it was but I was not sure. I really enjoy the air-play function. I have used volumio for a while but i think it's to buggy. This is the best working alternative for med right now =)

**Comment by marcelveldt** [comment]
OK, great to hear!
