### ISSUE TITLE
Won't accept credentials 

### ISSUE THREAD

**Issue by klattsy** [marcelveldt/plugin.audio.spotify#50]
Hi! On a raspberry pi 2 running Kodi 17.3 on OSMC. Add on worked perfectly first time but went back second time and it won't accept credentials.
This is the error:
21:06:52.397 T:1805845488   DEBUG: PushCecKeypress - ignored key  b
21:06:52.468 T:1958404096   DEBUG: ------ Window Deinit (DialogAddonSettings.xml) ------
21:06:52.720 T:1701417968   DEBUG: plugin.audio.spotify -->
21:06:52.720 T:1701417968   DEBUG: plugin.audio.spotify --> Couldn't request authentication token. Username/password error ? If you're using a facebook account with Spotify, make sure to generate a device account/password in the Spotify accountdetails.
21:06:53.309 T:1743623152   DEBUG: script.module.osmcsetting.updates :  - blurp 483 - MyMusicNav.xml
21:06:57.653 T:1805845488   DEBUG: PushCecKeypress - received key d8 duration 0 (rep:0 size:0)
21:06:57.653 T:1805845488   DEBUG: PushCecKeypress - added key d8
21:06:57.672 T:1958404096   DEBUG: OnKey: menu (0xd8) pressed, action is Back
21:06:57.680 T:1958404096   DEBUG: CGUIWindowManager::PreviousWindow: Deactivate
21:06:57.822 T:1701417968   DEBUG: plugin.audio.spotify -->
21:06:57.823 T:1701417968   DEBUG: plugin.audio.spotify --> Couldn't request authentication token. Username/password error ? If you're using a facebook account with Spotify, make sure to generate a device account/password in the Spotify accountdetails.
21:06:57.860 T:1805845488   DEBUG: PushCecKeypress - received key d8 duration 207 (rep:0 size:0)
21:06:57.860 T:1805845488   DEBUG: PushCecKeypress - ignored key d8

Have tried reinstalling but same thing.
Thanks,
Mark.

**Comment by marcelveldt** [comment]
Can you please send me a full Kodi log ? There should be some more logging from the add-on like the result of the platform discovery.

**Comment by klattsy** [comment]
Got it working mate. Thanks. Just trying to get it as a Spotify connect target. What are the conditions to get it working. Turn on in experimental setting then does phone and raspberry Pi have to Same wifi or same network? Can Bluetooth be used at all? Thanks for the add on.

**Comment by klattsy** [comment]
All good mate. Reinstalling everything fixed it. Have it working fantastic. As a connect device too. Will donate!

**Comment by marcelveldt** [comment]
great!
