### ISSUE TITLE
ERRO - Playing 30 SECONDS. 

### ISSUE THREAD

**Issue by diegopeixotostitch** [marcelveldt/plugin.audio.spotify#52]
My account is Premium, I already authenticated on the site, but the kodi plays only 30 seconds.

**Comment by wilderkaiser** [comment]
Hhi, i can NOT confirm this. Have this here working since mid of july without this isue.

**Comment by diegopeixotostitch** [comment]
It's the first time I install the application, it's Premium Account, I've already authenticated, but it only rings 30 seconds.

**Comment by marcelveldt** [comment]
Did you install the plugin from my repo ?
Most probably you installed some old version from some vague mirror site.

You should have version 1.1.42 or higher installed atm
