### ISSUE TITLE
Error when playing any song

### ISSUE THREAD

**Issue by pedroraptor** [marcelveldt/plugin.audio.spotify#54]
Hi, I just tried to play songs from this Spotify addon installed on my Kodi (from a raspberry PI - OS is libreelec) and they all crash.

Kodi displayed the usual error message, so I tried again while watching the logs and here they are:

21:36:07.373 T:1962504656   ERROR: CCurlFile::FillBuffer - Failed: Couldn't connect to server(7)
21:36:07.373 T:1962504656   ERROR: CCurlFile::Open failed with code 0 for http://localhost:52308/track/4ctyWIWWmWul4j1TDRbWVs/675
21:36:07.373 T:1962504656   ERROR: Open - failed to open source <http://localhost:52308/track/4ctyWIWWmWul4j1TDRbWVs/675>
21:36:07.373 T:1962504656   ERROR: Init: Error opening file http://localhost:52308/track/4ctyWIWWmWul4j1TDRbWVs/675
21:36:07.374 T:1962504656   ERROR: CAudioDecoder: Unable to Init Codec while loading file http://localhost:52308/track/4ctyWIWWmWul4j1TDRbWVs/675
21:36:07.374 T:1962504656 WARNING: PAPlayer::QueueNextFileEx - Failed to create the decoder
21:36:07.374 T:1962504656   ERROR: Playlist Player: skipping unplayable item: 0, path [http://localhost:52308/track/4ctyWIWWmWul4j1TDRbWVs/675]

My Spotify addon version is the latest (1.1.44) and I have a working premium Spotify account
Thanks for your help, and may I mention, I'm a huge fan of this addon, great work !

**Comment by marcelveldt** [comment]
things to try:

1) disable spotify connect support in the addon settings
2) look in your kodi log if there are more errors about the spotify addon (at startup)
