### ISSUE TITLE
Unable to Login

### ISSUE THREAD

**Issue by danen396** [marcelveldt/plugin.audio.spotify#56]
I have an issue where once after i install spotify and i try to login. Spotify doesnt show any error but i cannot see any of my playlist. all i see is 3 little "..."
please help

**Comment by danen396** [comment]
[kodi.log](https://github.com/marcelveldt/plugin.audio.spotify/files/1371499/kodi.log)
attached below is my log file. Please help

**Comment by adampelikan** [comment]
Hello,
I have same issue.
What could be the cause? I have only free account at Spotify, not the Spotify Premium...could it be the cause?

**Comment by adampelikan** [comment]
I had the same issue but than I read [here](https://forum.kodi.tv/showthread.php?tid=265356) that only premium account is supported.

**Comment by marcelveldt** [comment]
new version will be available on the repo within a few minutes, please test with that. Also remember that only Premium accounts are supported
