### ISSUE TITLE
Issue switching users

### ISSUE THREAD

**Issue by marcowindt** [marcelveldt/plugin.audio.spotify#58]
I'm not able to switch users when enabling and configuring multiple users. None of them are facebook related.
`12:29:45.512 T:1145115632 WARNING: Attempt to use invalid handle -1
12:29:45.846 T:1113584624 WARNING: plugin.audio.spotify --> Exception in plugin_content ! --> http status: 400, code:-1 - https://api.spotify.com/v1/users/********************:
                                             Invalid username`

It could be the same issue as:  #48 

Currently using version: 1.1.45

**Comment by marcelveldt** [comment]
Do you have any special characters in your usernames ?

**Comment by marcowindt** [comment]
No, my username is just my e-mail address. Which contains only alphanumeric characters and one dot and one '@' symbol.

**Comment by marcelveldt** [comment]
Will publish a new version later today in which this is fixed.

**Comment by marcowindt** [comment]
Great!
Thanks for your response!
