### ISSUE TITLE
Spotify Connect no longer working

### ISSUE THREAD

**Issue by disrupted** [marcelveldt/plugin.audio.spotify#59]
I was surprised to see my Kodi box (LibreELEC 8.2.1 Generic.x86_64) running this Spotify addon show up for the first time as a Spotify Connect device a few months ago. It used to work nicely but nowadays I can't get it to show up in my devices list from my computer or the mobile apps on Android/iOS anymore. I've updated the addon in the meantime and am now running the latest version 1.1.45 from this repository. Is anybody else experiencing this? Of course I am happy to provide log files if necessary.

**Comment by marcelveldt** [comment]
spotify connect must be enabled from the addon settings.

**Comment by disrupted** [comment]
I've had this enabled before already, but somehow it didn't show up. However I just updated the addon yesterday and now it's back up and running. I looked at the recent commits and saw you didn't even touch Spotify Connect but I am just glad it's working again (magic!).

**Comment by WildPenquin** [comment]
I can confirm Spotify connect does not work (tried to control KODI plugin computer from another Linux computer). Spotify Connect is enabled in KODI plugin settings (has been since last reboot and previously). Both clients can see each other, but controlling playback does not. Selecting the KODI machine from the desktop does mute playback on the desktop, though.

**Comment by WildPenquin** [comment]
Weird, after a reboot, it just started working again (I am sure I have  already done that before, many times, so there probably are conditions when this doesn't work although it should; maybe it needs a "fresh/new" session? Well, in any case, the feature is labeled "experimental" :-) ).

**Comment by jochym** [comment]
I'm afraid that something got changed by spotify. After recent update both spotify add-ons (this one and librespot) stopped working. Is there any hope for this to be fixed. The device shows up on the devices screen but if you try to connect to it you get "connecting..." and eventually the kodi box vanishes from the list.

**Comment by marcelveldt** [comment]
Yes, there was a change and I'll do my best to publish an update asap.

**Comment by jochym** [comment]
Librespot published the update - maybe you can base your modification on this?

**Comment by marcelveldt** [comment]
new version will be available on the repo within a few minutes
