### ISSUE TITLE
plugin incompatible

### ISSUE THREAD

**Issue by mmaverst** [marcelveldt/plugin.audio.spotify#63]
Hi,

I'm trying to install the plugin on my kodi instance. However, it tells me that the plugin is incompatible.
Are there any specific requirements for installing this plugin?

Kind regards

**Comment by marcelveldt** [comment]
install my repo. don't install directly from Github

**Comment by mmaverst** [comment]
I tried to install from your repository, but it wouldn't work. I clicked on your repository inside kodi but nothing happened.
I verified that it isn't a connection issue. How can I get some more logging on what's failing?
