### ISSUE TITLE
plugin not compatible

### ISSUE THREAD

**Issue by mmaverst** [marcelveldt/plugin.audio.spotify#64]
Hi,

Since you already closed my previous issue (and I can't seem to be able to re-open it) I am creating a new one.
I used the zip file from your repository. However, I still get an incompatible error.
I acquired some logging if that might be able to help you.

21:35:25 T:3019182080   DEBUG: Previous line repeats 3 times.
21:35:25 T:3019182080   DEBUG: OnKey: 11 (0x0b) pressed, action is Select
21:35:25 T:2778985392   DEBUG: webserver: request received for /jsonrpc
21:35:25 T:3019182080   DEBUG: ------ Window Deinit (FileBrowser.xml) ------
21:35:25 T:2778985392   DEBUG: webserver: request received for /jsonrpc
21:35:26 T:2804151216   DEBUG: FileManager, processing folder: zip://%2fhome%2fkodi%2frepository.marcelveldt-1.0.1.zip/repository.marcelveldt/
21:35:26 T:2804151216   DEBUG:   -- zip://%2fhome%2fkodi%2frepository.marcelveldt-1.0.1.zip/repository.marcelveldt/addon.xml
21:35:26 T:2804151216   DEBUG:   -- zip://%2fhome%2fkodi%2frepository.marcelveldt-1.0.1.zip/repository.marcelveldt/fanart.jpg
21:35:26 T:2804151216   DEBUG:   -- zip://%2fhome%2fkodi%2frepository.marcelveldt-1.0.1.zip/repository.marcelveldt/icon.png
21:35:26 T:2804151216   DEBUG: FileManager: create folder special://home/addons/repository.marcelveldt
21:35:26 T:2804151216   DEBUG: FileManager: copy zip://%2fhome%2fkodi%2frepository.marcelveldt-1.0.1.zip/repository.marcelveldt/addon.xml -> special://home/addons/repository.marcelveldt/addon.xml
21:35:26 T:2804151216   DEBUG: FileManager: copy zip://%2fhome%2fkodi%2frepository.marcelveldt-1.0.1.zip/repository.marcelveldt/fanart.jpg -> special://home/addons/repository.marcelveldt/fanart.jpg
21:35:26 T:2804151216   DEBUG: FileManager: copy zip://%2fhome%2fkodi%2frepository.marcelveldt-1.0.1.zip/repository.marcelveldt/icon.png -> special://home/addons/repository.marcelveldt/icon.png
21:35:26 T:3019182080   DEBUG: SECTION:UnloadDelayed(DLL: special://xbmcbin/system/ImageLib-arm.so)
21:35:26 T:3019182080   DEBUG: Unloading: /ImageLib-arm.so
21:35:26 T:2804151216    INFO: ADDON: cpluff: 'Could not read plug-in directory /usr/lib/kodi/addons: No such file or directory'
21:35:26 T:3019182080   DEBUG: ------ Window Init (DialogKaiToast.xml) ------
21:35:26 T:3019182080   DEBUG: SECTION:LoadDLL(special://xbmcbin/system/ImageLib-arm.so)
21:35:26 T:3019182080   DEBUG: Loading: /usr/lib/kodi/system/ImageLib-arm.so
21:35:26 T:2804151216   DEBUG: Checking repositories for updates (triggered by Exodus repository)
21:35:26 T:3019182080   DEBUG: ------ Window Init (DialogExtendedProgressBar.xml) ------
21:35:26 T:2692342704   DEBUG: CFileCache::Open - opening <tvaresolvers/tva-common-repository/raw/master/addons.xml.md5> using cache
21:35:26 T:2692342704   DEBUG: CurlFile::Open(0xa8d076f8) https://offshoregit.com/tvaresolvers/tva-common-repository/raw/master/addons.xml.md5
21:35:26 T:2692342704   ERROR: CCurlFile::FillBuffer - Failed: Couldn't resolve host name(6)
21:35:26 T:2692342704   ERROR: CCurlFile::Open failed with code 0 for https://offshoregit.com/tvaresolvers/tva-common-repository/raw/master/addons.xml.md5
21:35:26 T:2692342704   ERROR: Open - failed to open source <https://offshoregit.com/tvaresolvers/tva-common-repository/raw/master/addons.xml.md5>
21:35:26 T:2692342704   ERROR: Failed to fetch checksum for directory listing https://offshoregit.com/tvaresolvers/tva-common-repository/raw/master/addons.xml for repository repository.exodus.
21:35:26 T:2692342704   DEBUG: CFileCache::Open - opening <addons/isengard/addons.xml.md5> using cache
21:35:26 T:2692342704   DEBUG: CurlFile::Open(0xa8d0f008) http://mirrors.kodi.tv/addons/isengard/addons.xml.md5
21:35:26 T:2847929264  NOTICE: Thread FileCache start, auto delete: false
21:35:26 T:2847929264    INFO: CFileCache::Process - Hit eof.
21:35:26 T:2804151216    INFO: ADDON: cpluff: 'Could not read plug-in directory /usr/lib/kodi/addons: No such file or directory'
21:35:26 T:2847929264   DEBUG: Thread FileCache 2847929264 terminating
21:35:26 T:2692342704   DEBUG: Checksum for repository repository.xbmc.org not changed.
21:35:27 T:3019182080   DEBUG: CGUIMediaWindow::GetDirectory ()
21:35:27 T:3019182080   DEBUG:   ParentPath = []
21:35:27 T:2778985392   DEBUG: webserver: request received for /jsonrpc
21:35:27 T:2847929264  NOTICE: Thread BackgroundLoader start, auto delete: false
21:35:27 T:2847929264   DEBUG: Thread BackgroundLoader 2847929264 terminating
21:35:28 T:2778985392   DEBUG: webserver: request received for /jsonrpc

**Comment by marcelveldt** [comment]
minimum version of Kodi is Krypton, it might work on Jarvis. It will definitely not work on earlier versions.
