### ISSUE TITLE
Username&password are shown in process list / kodi crash logs

### ISSUE THREAD

**Issue by reox** [marcelveldt/plugin.audio.spotify#65]
See the code here:
https://github.com/marcelveldt/plugin.audio.spotify/blob/master/resources/lib/utils.py#L431-L436

The username and password are actually shown in plaintext in the process list (i.e. `ps aux`) for the spotty binary. This can be problematic, if the process list is accessible for other users.
It is also shown in crashlogs of kodi itself, which might also be problematic if someone submits bug reports and does remove it from the logs.

**Comment by marcelveldt** [comment]
that is because the mdns discovery feature (which uses spotify connect to get authentication) clashes with Kodi's builtin avahi support so for now the authentication is handled by passing username + password to the spotty binary.

**Comment by themalnz** [comment]
Hmmm, I'm seeing a pattern here with your posts … why do you answer every support query along the lines of … "you don't understand … or … you didn't do it right" ?

**Comment by marcelveldt** [comment]
??? Is this your way to respect a community driven project with endless of free private time spended?
