### ISSUE TITLE
Addon keeps raspberry crashing 

### ISSUE THREAD

**Issue by Shariner** [marcelveldt/plugin.audio.spotify#67]
If Addon is used as Spotify connect playback device or navigated by the Addon, the chosen song plays a few seconds (up to 5 seconds) and then the raspberry Crashs and reboot.

Appears every time

**Comment by marcelveldt** [comment]
What distro are you running on the Pi ? Did you try with latest/fresh version of libreelec ?
What version of the pi ?
Any clues in logs ?

**Comment by Shariner** [comment]
I own a Raspberry 3 model B, with latest Kodi and latest libreelec version.  I haven't done a fresh installation yet

I will send you the logs if i am home.

**Comment by Shariner** [comment]
Nothing unexpected at the logs

here they are: https://pastebin.com/T4nqsin5

I log me in, want to start a song and the pi crashs.

**Comment by tomtom30** [comment]
Same issue for me with 1.1.48 on raspberry and last osmc.
For me, osmc crash on startup directly.
I have nothing on logs

**Comment by marcelveldt** [comment]
new version will be available on the repo within a few minutes
