### ISSUE TITLE
no longer plays after "some fixes" in github master

### ISSUE THREAD

**Issue by benjidunn** [marcelveldt/plugin.audio.spotify#68]
After this commit https://github.com/marcelveldt/plugin.audio.spotify/commit/f2ea07327571b921eb94a6fc41a8b8266e9907e7 I am no longer able to play audio on a Raspberry Pi running OSMC.

It looks like the 'global' conf in httpproxy.py:run() is not being used. Without the commit, something is listening on 0.0.0.0:52308, but with it, something is listening on 127.0.0.1:8080 instead.

I have script.module.cherrypy version 11.0.1 installed.

**Comment by marcelveldt** [comment]
new version will be available on the repo within a few minutes
