### ISSUE TITLE
RPI3

### ISSUE THREAD

**Issue by Niruella** [marcelveldt/plugin.audio.spotify#7]
Hey there,
is there any easy way to get this working for my rpi3? I am not rly familiar with Python/Kodi yet.
Kind regards
Niruella

**Comment by marcelveldt** [comment]
Yes there is, it requires a little workaround however

http://forum.kodi.tv/showthread.php?tid=265356&pid=2289336#pid2289336

**Comment by Niruella** [comment]
Thank you very much! I will try it, may i ask u if i stuck anywhere?
