### ISSUE TITLE
Spotify Connect no longer working?

### ISSUE THREAD

**Issue by msbeintema** [marcelveldt/plugin.audio.spotify#70]
Hi Marcel, since the new Spotify update, my cell phone Spotify app will not cast to Kodi on my Raspberry Pi. However, my phone will serve as a target for Kodi. How can I (or you?) fix this?

**Comment by krulkrul** [comment]
I experience the same issue...was working fine...but now I cannot connect/stream from phone to Kodi

**Comment by marcelveldt** [comment]
There was an update in the Spotify code. I will post a new version later today

**Comment by disrupted** [comment]
@marcelveldt awesome, thanks for maintaining the addon

**Comment by madmodder123** [comment]
@marcelveldt How do I install the update from Github? The version on your repo is still on 1.1.46

**Comment by SeyedGH** [comment]
Any info about this? Is the spotty.exe code closedsource btw?

**Comment by heidi1303** [comment]
Spotty is OSS : https://github.com/michaelherger/spotty

**Comment by marcelveldt** [comment]
Spotty is indeed opensource. It's a modified version of Librespot, the well known opensource spotify connect player.

New update will be pushed asap. I'm still working out some quirks.

**Comment by gismo2004** [comment]
Are you going to push this on your repo too? Or just here on github?

**Comment by marcelveldt** [comment]
on the repo too

**Comment by msbeintema** [comment]
Marcel, thanks again for all the hard work. In awaitance of the push :)

**Comment by marcelveldt** [comment]
new version will be available on the repo within a few minutes
