### ISSUE TITLE
Spotty.exe crash when trying to connect Spotify Connect

### ISSUE THREAD

**Issue by risinek** [marcelveldt/plugin.audio.spotify#71]
Hi,
I just installed your plugin and I want to use it for Spotify Connect thing. I set it up in addon settings, and I'm able to see Kodi in available Spotify Connectdevices in Android Spotify app. But whenever I try to select it, it just shows Connecting in Android app. 
I found out, that whenever I try to connect to it, Spotty.exe crashes.
Running Kodi on Win 10 64 bit.
Is there anything I can help you with?

**Comment by Jesfreric** [comment]
Same for me. Running Kodi on a Raspi3 and trying to connect over Win64-bit Spotify app

**Comment by MinDBreaK** [comment]
He probably doesn't had time to fix it, he said that the code has been updated in #70

**Comment by marcelveldt** [comment]
new version will be available on the repo within a few minutes

**Comment by themalnz** [comment]
I'm still having these same issues over a year later and no updates from last year on any of this stuff ...

**Comment by marcelveldt** [comment]
That’s because I’m busy with my private life with 2 young kids, a new house and busy job. Not much time left to work on the community projects. I do what I can with the rare spare time but can’t do wonders. Hopefully some others chime in to help out. What issues are you experiencing?
