### ISSUE TITLE
Credentials prompt

### ISSUE THREAD

**Issue by loggio** [marcelveldt/plugin.audio.spotify#72]
Android: Nvidia Shield.
I cannot login since todays update.
I keep getting  "No credentials have been set or the login failed" 

I have a facebook account, but I'm using device ID username/password that was generated by Spotify.
trying to log in using my email address also gives the same error.

**Comment by marcelveldt** [comment]
Sorry, forgot some code for android devices auth.
New version will be up within an hour or so.
