### ISSUE TITLE
not able to play song

### ISSUE THREAD

**Issue by fportegies** [marcelveldt/plugin.audio.spotify#75]
After installing 1,1.52, navigating through menus works again. But when I press a song nothing happens. I am on kodi on raspberry pi. Logfile is added.
[kodi_log(2).txt](https://github.com/marcelveldt/plugin.audio.spotify/files/1866574/kodi_log.2.txt)

**Comment by marcelveldt** [comment]
What is selected as playback device? Perhaps you need to set it to your local device

**Comment by fportegies** [comment]
That did the job. Thanks for this great add-on. Groet, Frank

Op zo 1 apr. 2018 20:43 schreef Marcel van der Veldt <
notifications@github.com>:

**Comment by undrline** [comment]
This same issue is happening with me ... can navigate, but not play.  No errors; tapping does nothing.
By default, on installation, playback device seemed odd: listing says "Playback device: Spotify Connect" but clicking on it has "Local playback" as "[Active]"
Switching playback devices seems to fix the mismatch between the two listings.
Not sure how to set as truly local ... "Local playback using remote host localhost" doesn't work

Kodi Krypton 17.6 (No build.  Addons installed: Placenta, Trakt)
Current plugin.audio.spotify installed from zip here (sorry, not sure where to see version number)
Android 5.1.1 
Samsung Galaxy Core Prime (SM-G360T1) mobile device

**Comment by maurisso** [comment]
I am in the same situation, can't plat with kodi.
