### ISSUE TITLE
No sound or visualisation movement. LibreELEC 17.6 ARM (S812)

### ISSUE THREAD

**Issue by kfm16** [marcelveldt/plugin.audio.spotify#76]
Hi,

I love this add on but it's stopped working entirely! I can browse (faster now after .52) but now nothing plays! Kodi thinks it's playing and the time counts up as if it's playing but no sound is heard and the visualisation is still!!

Other add ons and my radio / tvheadend works perfectly.

I've uploaded a log here (I don't know if I did it right, I tried to follow the instructions I found...).    https://securesha.re?#u=3931b74c3b2c8db218ed09190500acae.bin&p=cEsVdiweFfw1-FyHK8L-Q5kaTwqnKeisvT4gAGoZmQY

I hope this isn't anything too complicated ...

Thank you for your time!!

**Comment by marcelveldt** [comment]
What is selected as the playback target ? If it's set to Spotify Connect it might be playing on another device out of your sight. Set it to "use local device for playback" if you want the audio to be played by Kodi.

**Comment by kfm16** [comment]
I disabled that function and it only had local as an option....

**Comment by marcelveldt** [comment]
Hmm, strange. Nothing in your log that indicates an error. It looks perfectly fine and it should be playing. Maybe try to reset the addon to default settings ?

**Comment by kfm16** [comment]
I just reset the add-on but no luck, it it like it's playing a silent song if that makes sense?

Playback devices only has 1 option which is "Local playback on this device [Active]"

I tried toggling the use as target option just in case but no luck with that too...

What dependencies does it use? (I could try resetting them??

**Comment by marcelveldt** [comment]
Did you use your phone to authenticate or username/password ?

**Comment by kfm16** [comment]
Username/Password ... I Didn't know you can use a phone!

**Comment by marcelveldt** [comment]
btw version 1.1.53 is now on the repo, make sure to test with that as I changed some stuff

**Comment by kfm16** [comment]
.53 didn't fix it sadly :(

I can't seem to find how to upload to GitHub on phone (I don't have a computer) so I hope this is ok?

https://securesha.re?#u=b399e5a3bbe05d176a0b5f43f5ce7598.bin&p=Urp-6vWPgVJCSxR1Bi8PU8Iink62xXT2r4XiM4oAELI

**Comment by kfm16** [comment]
http://ix.io/15IS might be better?

**Comment by marcelveldt** [comment]
version 1.1.55 will be on the repo within a few minutes. Please test if that fixes the issue.

**Comment by kfm16** [comment]
All fixed now, thank you ever so much for your time!!

**Comment by marcelveldt** [comment]
great!
