### ISSUE TITLE
cannot browse playlists or albums

### ISSUE THREAD

**Issue by fportegies** [marcelveldt/plugin.audio.spotify#77]
Since version 1.1.55 cannot browser playlists or albums. Spotify keeps searching, is busy.
Logfile is supplied.
[kodi_log(3).txt](https://github.com/marcelveldt/plugin.audio.spotify/files/1873080/kodi_log.3.txt)

**Comment by wechsler42** [comment]
Hi Marcel and Frank,
I can confirm Frank's observations. I did not change anything on my system and "all over sudden" the Spotify plugin worked as before.
Please keep on your good work on the plugin!
