### ISSUE TITLE
Cannot play on Raspberry Pi2 (LibreELEC) after upgrading to 1.0.20

### ISSUE THREAD

**Issue by ehcoolguy** [marcelveldt/plugin.audio.spotify#8]
First of all, that's really a great plugin!

It's strange that after upgrading to 1.0.20 (I am very sure I didn't change anything), my spotify (RPi2 powered by LibreELEC) cannot play more that 12 seconds (around), every playlist, every album, even every song. My testing results are:
1. I have tried to uninstall, remove the plugin and clean all user data as well.
2. Ver. 1.0.20 on RPi2 powered by LibreELEC, music will stop around 12 seconds, all songs. (Precisely, it will "mute" after 12 seconds, but the progress bar won't stop.)
3. Ver. 1.0.20 on Windows 7 (Kodi 16.0), music plays correctly.
4. Ver. 1.0.19 on RPi2 powered by LibreELEC, music plays correctly.

So I downgrade to 1.0.19 (Also disabling auto-update). Attaching a screenshot for your reference. Could you help me to verify if this is my configuration mistake or something wrong with 1.0.20?

Thanks.
![2016-09-04_14-29-09](https://cloud.githubusercontent.com/assets/8525258/18229645/ce364976-72b3-11e6-9a2c-2551bfab6495.jpg)

**Comment by marcelveldt** [comment]
I can confirm the issue. Will look into it later today
