### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by remyr024** [marcelveldt/plugin.audio.spotify#9]
Beste Marcel,
Top plugin, werkt top op m'n laptop. 
Ik zit alleen met een probleem. Ik wil de spotify plugin ook gebruiken op mijn m8S+ die loopt op openelec, maar telkens als ik inlog geeft hij dit aan: "Login error: Er is geen ondersteunende browser gevonden voor het authorizatieverzoek naar Spotify." Heb jij enig idee hoe ik dit kan oplossen? De spotify plugin zou mijn kodi setup namelijk helemaal compleet maken. 

b.v.d.

**Comment by marcelveldt** [comment]
Hoi, sorry voor de late reactie. Heb je nog steeds problemen ?
