### ISSUE TITLE
Volume randomly to 50%

### ISSUE THREAD

**Issue by SeyedGH** [marcelveldt/plugin.audio.spotify#91]
Hello since yesterday the volume is getting to 50% randomly after disabling the add-on it did not happen again anything changed?

**Comment by zoodleGH** [comment]
I've had the same, the add-on is currently disabled and volume has remained set to the level I want.  Found these lines in the KODI.LOG:
18:14:33.130 T:1497363360   DEBUG: plugin.audio.spotify --> lms event hook called. Event: [u'spottyconnect', u'volume', 50]
18:14:33.155 T:1497363360   DEBUG: plugin.audio.spotify --> volume change detected on connect player: 50
18:14:33.160 T:1944912800   DEBUG: CAnnouncementManager - Announcement: OnVolumeChanged from xbmc
18:14:33.160 T:1944912800   DEBUG: GOT ANNOUNCEMENT, type: 64, from xbmc, message OnVolumeChanged

Not sure if that helps.

**Comment by gismo2004** [comment]
As far as I have seen this happens after getting a new token. I have not checked the code yet, but I guess this is somehow hard-coded in spotty/librespot

**Comment by syaifulnizamyahya** [comment]
Me too. For now I have to disable spotify or create new profile for spotify

**Comment by tug912** [comment]
Hi ! Same problem for me ! Sound dicrease of 50 % each time i reboot. 
More of all i only have spotify addon installed ! I never used it !

**Comment by tent-icle** [comment]
I can also confirm this issue since the upgrade to 1.1.57 about 3 days ago. My debug logs seem to show it beginning at pretty much the same time as obtaining a new token. 

Interestingly, in my testing I have found the issue occurs about 90% of the time. About 10% of the time I am able to enable the addon without any impact to the volume.

**Comment by gismo2004** [comment]
I don't think that the volume implementation is a good idea currently. Librespot is cashing the last stored volume in a file to be loaded after restart. But if kodi changes the volume librespot is not informed about this change, so after reboot or better "spotty restart" the stored volume gets set to kodi again. 

If you don't like this, a easy way to workaround: comment out line 70 in 
plugin.audio.spotify/resources/lib/httpproxy.py

xbmc.executebuiltin("SetVolume(%s,true)" % vol_level)

Cheers

**Comment by marcelveldt** [comment]
new version will be on the repo within a few minutes with this disabled, it clearly needs more work
